"use client";
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {tripSchema} from '@/lib/form-schemas';
import {supabase} from '@/lib/supabase';
import {PlanStreamError,readPlanStream} from '@/lib/plan-stream';
import {rememberItinerary} from '@/lib/travel-store';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Check, Sparkles, Save, MapPin } from 'lucide-react';
import destinations from '@/data/destinations.json';
import { DEMO_TRIP, TRIP_STORAGE_KEY, SAVED_TRIP_STORAGE_KEY, formatINR, getTripDuration, dateAt, defaultTrip, currentDraft, todayDate } from '@/lib/trip';
import { parseTrip, INTERESTS, ACCESS, AVOID } from '@/lib/trip-validation';
import type { TripForm } from '@/types/travel';
const STEPS=['The essentials','Your travel style','Comfort & logistics','Review & create'];
export default function Planner(){
 const [progress,setProgress]=useState(''),[preview,setPreview]=useState<{day:number;title:string;activities:{name:string;time:string}[]}[]>([]);
 const [trip,setTrip]=useState<TripForm>(DEMO_TRIP),[step,setStep]=useState(0),[ready,setReady]=useState(false),[error,setError]=useState(''),[suggestedBudget,setSuggestedBudget]=useState<number|null>(null),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 useEffect(()=>{let draft=defaultTrip();try{const raw=localStorage.getItem(TRIP_STORAGE_KEY);if(raw)draft={...draft,...JSON.parse(raw)};}catch{}const p=new URLSearchParams(location.search);const dest=p.get('destination');if(dest&&destinations.some(d=>d.name===dest))draft.destination=dest;const date=p.get('startDate');if(date&&/^\d{4}-\d{2}-\d{2}$/.test(date)&&!Number.isNaN(Date.parse(date))){draft.startDate=date;draft.endDate=dateAt(date,4);}if(p.has('budget')&&Number(p.get('budget'))>=1000)draft.budget=Number(p.get('budget'));setTrip(currentDraft(draft));setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(TRIP_STORAGE_KEY,JSON.stringify(trip));}catch{setError('Your browser could not save the draft. You can still generate a plan.');}setSaved(false);},[trip,ready]);
 const {handleSubmit}=useForm<TripForm,unknown,TripForm>({values:trip,resolver:zodResolver(tripSchema)});
 function update<K extends keyof TripForm>(key:K,value:TripForm[K]){setTrip(t=>({...t,[key]:value}));setError('');}
 function toggle(key:'interests'|'accessibility'|'avoid'|'hotelAmenities',value:string){const values=(trip[key]||[]) as string[];update(key,(values.includes(value)?values.filter(x=>x!==value):[...values,value]) as never);}
 function validate(){try{return parseTrip(trip);}catch(e){setError(e instanceof Error?e.message:'Check your trip details.');return null;}}
 function next(){if(!validate())return;setStep(s=>Math.min(3,s+1));window.scrollTo({top:0,behavior:'smooth'});}
 async function generate(){const t=validate();if(!t)return;setBusy(true);setError('');setSuggestedBudget(null);setPreview([]);setProgress('TravelSetu is creating your itinerary…');const abort=new AbortController();const timeout=setTimeout(()=>abort.abort(),175000);try{const gateway=process.env.NEXT_PUBLIC_GATEWAY_URL;const session=gateway?await supabase()?.auth.getSession():null;const endpoint=gateway?new URL('/v1/plan',gateway).toString():'/api/gemini';const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json',Accept:'text/event-stream',...(session?.data.session?{Authorization:'Bearer '+session.data.session.access_token}:{})},body:JSON.stringify({trip:t}),signal:abort.signal});let result:any;await readPlanStream(r,(event,data)=>{if(event==='status')setProgress(data.message);if(event==='day')setPreview(old=>[...old.filter(d=>d.day!==data.day),data]);if(event==='complete')result=data;});if(!result?.itinerary)throw new Error('Gemini did not return a completed plan.');localStorage.setItem('travelsetu_trip',JSON.stringify(t));localStorage.setItem(TRIP_STORAGE_KEY,JSON.stringify(t));rememberItinerary(result.itinerary);localStorage.setItem('travelsetu_itinerary_source',result.source||'travelsetu');window.location.href='/itinerary';}catch(e){if(e instanceof PlanStreamError&&e.code==='BUDGET_EXCEEDED'&&Number.isFinite(e.suggestedBudget))setSuggestedBudget(e.suggestedBudget!);setError(e instanceof Error&&e.name==='AbortError'?'Planning took too long. Your draft is saved.':e instanceof Error?e.message:'Could not finish the plan.');}finally{clearTimeout(timeout);setBusy(false);}}
 function save(){const t=validate();if(!t)return;try{const raw=JSON.parse(localStorage.getItem(SAVED_TRIP_STORAGE_KEY)||'[]');const previous=Array.isArray(raw)?raw:[];localStorage.setItem(SAVED_TRIP_STORAGE_KEY,JSON.stringify([{id:crypto.randomUUID(),createdAt:new Date().toISOString(),...t},...previous].slice(0,50)));localStorage.setItem('travelsetu_trip',JSON.stringify(t));setSaved(true);}catch{setError('Your browser could not save the trip.');}}
 const d=destinations.find(d=>d.name===trip.destination),duration=getTripDuration(trip.startDate,trip.endDate);
 return <main className="page-shell"><div className="container-page"><p className="eyebrow">The best trips start with you</p><h1 className="page-title">Plan your next chapter.</h1><p className="muted">Your preferences. A day-by-day plan created by Gemini.</p>
  <ol className="my-8 grid grid-cols-2 gap-3 lg:grid-cols-4">{STEPS.map((s,i)=><li key={s}><button onClick={()=>{if(i<step)setStep(i);}} disabled={i>step||busy} aria-current={step===i?'step':undefined} className={`flex w-full items-center gap-3 rounded-2xl border p-4 text-left text-sm font-bold ${step===i?'border-[#075b3d] bg-[#075b3d] text-white':'border-slate-200 bg-white'}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border border-current">{i<step?<Check size={15}/>:i+1}</span>{s}</button></li>)}</ol>
  <div className="grid items-start gap-6 lg:grid-cols-[1fr_300px]"><form className="panel" onSubmit={handleSubmit(()=>{if(step<3)next();else generate();},errors=>setError(errors.root?.message||'Check your trip details.'))}>
   {step===0&&<><fieldset className="mb-8"><legend className="text-xl font-bold">What would you love to discover?</legend><p className="mt-2 text-sm muted">Choose this first. It shapes your places, food and free time.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{([['local','Live like a local','Neighbourhoods, regional food, craft and everyday culture.'],['balanced','A little of both','Local discoveries alongside the best-known sights.'],['highlights','The famous highlights','Landmarks and classic experiences, with familiar meal choices.']] as const).map(([value,title,copy])=><button type="button" key={value} aria-pressed={trip.experienceMode===value} onClick={()=>update('experienceMode',value)} className={`rounded-2xl border p-4 text-left ${trip.experienceMode===value?'border-blue-600 bg-blue-50':'border-slate-200'}`}><strong className="block">{title}</strong><span className="mt-2 block text-sm muted">{copy}</span></button>)}</div></fieldset><Title title="The essentials" description="Your dates include arrival and departure. The budget is for everyone in your group."/><div className="field-grid mt-7"><Field label="Starting city" required value={trip.from} onChange={v=>update('from',v)} placeholder="e.g. Dehradun"/><Select label="Destination" value={trip.destination} options={destinations.map(d=>d.name)} onChange={v=>update('destination',v)}/><Field label="Arrival date" type="date" min={todayDate()} value={trip.startDate} onChange={v=>{update('startDate',v);if(v>trip.endDate)update('endDate',dateAt(v,4));}} required/><Field label="Departure date" type="date" value={trip.endDate} min={trip.startDate} onChange={v=>update('endDate',v)} required/><Field label="Total travellers (including children)" type="number" min={1} max={20} value={trip.travellers} onChange={v=>{update('travellers',Number(v));update('roomCount',Math.max(1,Math.ceil(Number(v)/2)));}}/><Field label="Whole group budget · ₹" type="number" min={1000} max={10000000} value={trip.budget} onChange={v=>update('budget',Number(v))}/><Select label="Who is travelling?" value={trip.groupType||'Friends'} options={['Solo','Couple','Friends','Family','Work trip']} onChange={v=>update('groupType',v)}/><Select label="This budget covers" value={trip.budgetScope||'whole-trip'} options={['whole-trip','at-destination']} labels={['Whole trip, including intercity travel','Stay, food and activities at destination']} onChange={v=>update('budgetScope',v as TripForm['budgetScope'])}/><Field label="Children in the group" type="number" min={0} max={19} value={trip.children||0} onChange={v=>update('children',Number(v))}/><Field label="Senior travellers in the group" type="number" min={0} max={20} value={trip.seniors||0} onChange={v=>update('seniors',Number(v))}/></div><p className="mt-5 text-sm muted">Children and senior travellers are included in your total traveller count. The planner supports up to 14 calendar days.</p></>}
   {step===1&&<><Title title="What does a good trip feel like?" description="Your answers shape the places we pick and how much goes into each day."/><Chips label="What draws you in?" options={INTERESTS} values={trip.interests} toggle={v=>toggle('interests',v)}/><div className="field-grid mt-7"><Select label="Travel pace" value={trip.travelStyle} options={['Relaxed','Balanced','Packed']} onChange={v=>update('travelStyle',v as TripForm['travelStyle'])}/><Select label="Food preference" value={trip.foodPreference} options={['Any','Vegetarian','Non-Veg','Vegan']} onChange={v=>update('foodPreference',v as TripForm['foodPreference'])}/><Field label="Start my day at" type="time" value={trip.dayStartTime||'08:30'} onChange={v=>update('dayStartTime',v)}/><Field label="Finish activities by" type="time" value={trip.dayEndTime||'20:00'} onChange={v=>update('dayEndTime',v)}/><Field label="Daily walking limit · km" type="number" min={0} max={20} value={trip.walkingLimitKm??5} onChange={v=>update('walkingLimitKm',Number(v))}/><Field label="Dietary notes / allergies" value={trip.dietaryNotes||''} onChange={v=>update('dietaryNotes',v)} placeholder="e.g. Jain food, peanut allergy"/></div><Chips label="I would rather avoid" options={AVOID} values={trip.avoid||[]} toggle={v=>toggle('avoid',v)}/><label className="mt-7 block"><span className="label">Places I don’t want to miss</span><textarea className="input" maxLength={500} value={trip.mustVisit||''} onChange={e=>update('mustVisit',e.target.value)} placeholder={`e.g. ${d?.activities.slice(0,2).join(', ')}`}/></label></>}
   {step===2&&<><Title title="The practical details" description="Arrival times, rest breaks and transport matter as much as the sights."/><div className="field-grid mt-7"><Field label="Arrive at destination around" type="time" value={trip.arrivalTime||'10:00'} onChange={v=>update('arrivalTime',v)}/><Field label="Leave destination around" type="time" value={trip.departureTime||'18:00'} onChange={v=>update('departureTime',v)}/><Select label="Travel to destination by" value={trip.transport} options={['Any','Train','Bus','Flight','Car']} onChange={v=>update('transport',v as TripForm['transport'])}/><Select label="Getting around locally" value={trip.localTransport||'Mix of walking and taxis'} options={['Mix of walking and taxis','Mostly walking','Public transport','Private cab']} onChange={v=>update('localTransport',v)}/><Select label="Where would you like to stay?" value={trip.accommodationPreference} options={['Comfortable stay','Budget stay','Hostel / homestay','Premium stay']} onChange={v=>update('accommodationPreference',v)}/><Field label="Rooms needed" type="number" min={1} max={20} value={trip.roomCount||1} onChange={v=>update('roomCount',Number(v))}/><Field label="Budget reserve · %" type="number" min={0} max={30} value={trip.reservePercent??10} onChange={v=>update('reservePercent',Number(v))}/></div><div className="mt-6"><Field label="Find food and stays within · km of a planned stop" type="number" min={1} max={10} value={trip.nearbyRadiusKm||3} onChange={v=>update('nearbyRadiusKm',Number(v))}/><label className="mt-5 flex items-start gap-3 text-sm"><input type="checkbox" checked={trip.autoAdjust!==false} onChange={e=>update('autoAdjust',e.target.checked)} className="mt-1 h-5 w-5"/><span><strong>Automatically adjust for available conditions</strong><br/>Use dated forecasts and reported disruptions to pause affected visits or allow more travel time. Every change stays visible.</span></label></div><Chips label="Useful accommodation amenities" options={['Wi-Fi','Breakfast','Parking','Air conditioning','Lift','Kitchen','Pool']} values={trip.hotelAmenities||[]} toggle={v=>toggle('hotelAmenities',v)}/><Chips label="Access and comfort needs" options={ACCESS} values={trip.accessibility||[]} toggle={v=>toggle('accessibility',v)}/><label className="mt-7 block"><span className="label">Anything else we should plan around?</span><textarea className="input" value={trip.specialRequirements} maxLength={500} onChange={e=>update('specialRequirements',e.target.value)} placeholder="Celebrations, work calls, long rest breaks…"/></label><p className="mt-3 text-sm muted">Access and allergy requirements need direct confirmation with venues and suppliers.</p></>}
   {step===3&&<><Title title="This is your starting point" description="Check the details. Your itinerary will keep time for meals, getting around and taking a breath."/><div className="mt-7 grid gap-3 sm:grid-cols-2">{[['Experience',trip.experienceMode||'balanced'],['Nearby search',`${trip.nearbyRadiusKm||3} km from stops`],['Adjustments',trip.autoAdjust!==false?'Automatic, with a change log':'Review suggestions first'],['Journey',`${trip.from} → ${trip.destination}`],['Dates',`${trip.startDate} → ${trip.endDate}`],['Duration',`${duration} days · ${Math.max(0,duration-1)} nights`],['Group',`${trip.travellers} people · ${trip.children||0} children · ${trip.seniors||0} seniors`],['Budget',`${formatINR(trip.budget)} · ${trip.reservePercent}% reserve`],['Pace',`${trip.travelStyle} · ${trip.dayStartTime}–${trip.dayEndTime}`],['Food',`${trip.foodPreference}${trip.dietaryNotes?` · ${trip.dietaryNotes}`:''}`],['Stay',`${trip.accommodationPreference} · ${trip.roomCount} rooms`],['Transport',`${trip.transport} · ${trip.localTransport}`],['Access',trip.accessibility?.join(', ')||'No specific needs'],['Avoid',trip.avoid?.join(', ')||'No exclusions'],['Must-see',trip.mustVisit||'Open to suggestions'],['Amenities',trip.hotelAmenities?.join(', ')||'No preference'],['Walking',`${trip.walkingLimitKm} km/day maximum`],['Arrival / departure',`${trip.arrivalTime} / ${trip.departureTime}`],['Other notes',trip.specialRequirements||'None']].map(([label,value])=><div className="rounded-xl bg-[#f1f5ee] p-4" key={label}><p className="text-xs uppercase tracking-wide muted">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><p className="notice mt-6">The plan uses estimated group costs. Available weather and disruption reports are checked during planning. Hotel availability and venue hours still require confirmation; an itinerary does not make a reservation.</p></>}
   {suggestedBudget&&<div className="notice mt-5"><p>The proposed plan needs a higher budget. This is an estimate for that plan, not a verified minimum fare.</p><label className="mt-3 block">Group budget · ₹<input className="input mt-1" type="number" min={1000} max={10000000} value={trip.budget} onChange={e=>update('budget',Number(e.target.value))}/></label><button type="button" className="btn-secondary mt-3" onClick={()=>{update('budget',suggestedBudget);setError('');setSuggestedBudget(null);}}>Use {formatINR(suggestedBudget)} and review</button><button type="button" className="ml-3 text-sm underline" onClick={()=>{update('accommodationPreference','Budget stay');update('transport','Any');update('localTransport','Public transport');setSuggestedBudget(null);setError('Cheaper preferences selected. Generate again to ask Gemini for a simpler plan.');}}>Keep budget & try cheaper options</button></div>}
   {error&&<p role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800">{error}</p>}
   <div className="mt-8 flex flex-wrap justify-between gap-3 border-t pt-6"><button className="btn-secondary" type="button" disabled={step===0||busy} onClick={()=>setStep(s=>s-1)}><ArrowLeft size={16}/> Back</button><div className="flex flex-wrap gap-3">{step===3&&<button type="button" className="btn-secondary" disabled={busy} onClick={save}>{saved?<Check size={16}/>:<Save size={16}/>} {saved?'Saved':'Save trip'}</button>}<button className={step===3?'btn-yellow':'btn-primary'} disabled={busy||!ready}>{step===3?<Sparkles size={17}/>:null}{busy?'Building your detailed plan…':step===3?'Generate itinerary':'Continue'}{step<3&&<ArrowRight size={16}/>}</button></div></div><div role="status" aria-live="polite" className="mt-3 text-sm muted">{busy?progress:''}</div>
  {preview.length>0&&<section className="mt-5 space-y-3" aria-label="Generation preview"><p className="text-xs muted">Draft preview · available after the complete plan passes checks.</p>{preview.map(d=><details className="quiet-details" key={d.day}><summary>Day {d.day} · {d.title}</summary><ul className="space-y-2 text-sm muted">{d.activities.map((a,i)=><li key={i}>{a.time} · {a.name}</li>)}</ul></details>)}</section>}</form><aside className="panel lg:sticky lg:top-24"><MapPin size={25} className="text-[#075b3d]"/><h2 className="mt-3 text-2xl font-bold">{trip.destination}</h2><p className="mt-2 text-sm muted">{d?.state}</p><dl className="mt-6 space-y-4 text-sm"><div className="flex justify-between"><dt>Calendar days</dt><dd className="font-bold">{duration||'Check dates'}</dd></div><div className="flex justify-between"><dt>Travellers</dt><dd className="font-bold">{trip.travellers}</dd></div><div className="flex justify-between"><dt>Group budget</dt><dd className="font-bold">{formatINR(trip.budget)}</dd></div></dl><details className="mt-5 border-t pt-4 text-sm muted"><summary>Getting there</summary><p className="mt-3">{d?.gettingThere}</p></details><Link href="/explore" className="mt-5 block text-sm font-bold text-[#075b3d]">Still choosing? Explore India →</Link><p className="mt-5 text-xs muted">Your draft is saved in this browser. It isn’t synced to your friend’s device.</p></aside></div></div></main>;
}
function Title({title,description}:{title:string;description:string}){return <div><h2 className="text-2xl font-bold">{title}</h2><details className="mt-2 text-sm muted"><summary>Planning tip</summary><p className="mt-2">{description}</p></details></div>}
function Field({label,onChange,...props}:{label:string;onChange:(value:string)=>void}&Omit<React.InputHTMLAttributes<HTMLInputElement>,'onChange'>){return <label><span className="label">{label}</span><input className="input" {...props} onChange={e=>onChange(e.target.value)}/></label>}
function Select({label,value,options,labels,onChange}:{label:string;value:string;options:readonly string[];labels?:string[];onChange:(value:string)=>void}){return <label><span className="label">{label}</span><select className="input" value={value} onChange={e=>onChange(e.target.value)}>{options.map((o,i)=><option key={o} value={o}>{labels?.[i]||o}</option>)}</select></label>}
function Chips({label,options,values,toggle}:{label:string;options:readonly string[];values:readonly string[];toggle:(v:string)=>void}){return <fieldset className="mt-7"><legend className="label">{label}</legend><div className="mt-3 flex flex-wrap gap-2">{options.map(o=><button type="button" className="chip" aria-pressed={values.includes(o)} onClick={()=>toggle(o)} key={o}>{values.includes(o)&&<Check size={14}/>} {o}</button>)}</div></fieldset>}
