'use client';
import {useState} from 'react';
import Link from 'next/link';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import {supabase,cloudConfigured} from '@/lib/supabase';
import {Button} from './ui/button';
import {Input} from './ui/input';
const schema=z.object({email:z.email('Enter a valid email'),password:z.string().min(8,'Use at least 8 characters').max(128)});
export default function AuthForm({signup=false}:{signup?:boolean}){const [message,setMessage]=useState('');const {register,handleSubmit,formState:{errors,isSubmitting}}=useForm<z.infer<typeof schema>>({resolver:zodResolver(schema)});async function submit(v:z.infer<typeof schema>){setMessage('');const client=supabase();if(!client){setMessage('Supabase is not configured yet. Add its public URL and anon key, then restart the app.');return;}try{const {data,error}=signup?await client.auth.signUp({email:v.email,password:v.password,options:{emailRedirectTo:location.origin+'/account'}}):await client.auth.signInWithPassword(v);if(error)throw error;if(data.session)window.location.href='/account';else setMessage('Check your email to confirm your account, then sign in.');}catch(e){setMessage(e instanceof Error?e.message:'Authentication could not finish.');}}
 return <main className="page-shell"><div className="container-page max-w-lg"><div className="panel"><p className="eyebrow">Your trips, wherever you go</p><h1 className="mt-3 text-3xl font-black">{signup?'Create your account':'Welcome back'}</h1><p className="mt-3 text-sm muted">Save trips, expenses, private photos and reviews to your own account.</p>{!cloudConfigured()&&<p className="notice mt-4">Cloud accounts need Supabase setup. You can keep planning locally.</p>}<form className="mt-6 space-y-5" onSubmit={handleSubmit(submit)}><label className="block"><span className="label">Email</span><Input type="email" autoComplete="email" {...register('email')}/>{errors.email&&<span className="text-xs text-red-700">{errors.email.message}</span>}</label><label className="block"><span className="label">Password</span><Input type="password" autoComplete={signup?'new-password':'current-password'} {...register('password')}/>{errors.password&&<span className="text-xs text-red-700">{errors.password.message}</span>}</label><Button disabled={isSubmitting} className="w-full">{isSubmitting?'Please wait…':signup?'Create account':'Sign in'}</Button></form>{message&&<p role="status" className="notice mt-4">{message}</p>}<p className="mt-5 text-sm"><Link className="font-bold text-blue-700" href={signup?'/login':'/signup'}>{signup?'Already registered? Sign in':'New here? Create an account'}</Link></p><Link className="mt-4 block text-sm muted" href="/plan-trip">Continue planning without an account →</Link></div></div></main>;
}
