'use client';
import Link from 'next/link';
import {useState} from 'react';
import {Landmark,Flower2,Trees,Mountain,Sun,Compass,ArrowRight,Utensils,Palette,Leaf,Shirt,Factory,Wheat,Map,Flag,BookOpen,Users,Globe2} from 'lucide-react';
import ReferencePhoto from './ReferencePhoto';
const moods=[{name:'Historic',interest:'Culture',icon:Landmark,tone:'peach'},{name:'Spiritual',interest:'Spiritual',icon:Flower2,tone:'rose'},{name:'Nature',interest:'Nature',icon:Trees,tone:'mint'},{name:'Adventure',interest:'Adventure',icon:Mountain,tone:'aqua'},{name:'Slow escapes',interest:'Romantic',icon:Sun,tone:'lavender'},{name:'All journeys',interest:'All',icon:Compass,tone:'blue'}];
const sights=[{name:'Taj Mahal',area:'Agra, Uttar Pradesh',id:'agra',x:150},{name:'Basilica of Bom Jesus',area:'Goa',id:'goa',x:865},{name:'Batasia Loop',area:'Darjeeling, West Bengal',id:'darjeeling',x:1223},{name:'India Gate',area:'New Delhi',id:'delhi',x:1580}];
const craftKinds=[{name:'Agriculture',icon:Wheat},{name:'Food',icon:Utensils},{name:'Handicraft',icon:Palette},{name:'Handloom',icon:Shirt},{name:'Textile',icon:Leaf},{name:'Manufacturing',icon:Factory}];
const crafts=[{name:'Coconut traditions',area:'Coastal India',kind:'Agriculture',x:121,copy:'Look for coconut products in coastal markets and ask how they are made.'},{name:'Regional flavours',area:'Coastal kitchens',kind:'Food',x:490,copy:'Discover a regional recipe and ask which ingredients are grown nearby.'},{name:'Palm-leaf craft',area:'Artisan markets',kind:'Handicraft',x:858,copy:'Meet makers, ask about materials and look for handmade details.'},{name:'Coir & coconut',area:'Coastal workshops',kind:'Manufacturing',x:1226,copy:'Explore the making of coir goods. Arrange workshop visits in advance.'},{name:'Woven stories',area:'Local textile markets',kind:'Textile',x:1593,copy:'Ask about the weave, origin and care instructions before buying.'},{name:'Handloom traditions',area:'Weavers & cooperatives',kind:'Handloom',x:1593,copy:'A cooperative or working loom offers a closer look at a weaving tradition.'}];
const facts=[{name:'At a glance',icon:Globe2,title:'One country. Many ways to explore.',copy:'Start with a region, then follow its landscapes, food and local traditions. Your favourite discovery may be a small neighbourhood.',link:'https://knowindia.india.gov.in/'},{name:'People & culture',icon:Users,title:'Leave room for a conversation.',copy:'Languages, customs and food traditions vary across India. Ask before photographing people and follow local etiquette.',link:'https://knowindia.india.gov.in/culture-and-heritage/'},{name:'Landscapes',icon:Map,title:'From peaks to coastlines.',copy:'Mountains, plains, forests, deserts and islands create very different journeys. Match your pace to the terrain.',link:'https://knowindia.india.gov.in/profile/physical-features.php'},{name:'National days',icon:Flag,title:'15 August · Independence Day',copy:'Explore stories of independence through museums, memorials and heritage walks. Check local access before visiting.',link:'https://knowindia.india.gov.in/independence-day-celebration/'},{name:'Travel thoughtfully',icon:BookOpen,title:'Be a guest. Leave a good story.',copy:'Support local makers, respect places of worship, use refillable bottles and leave natural places as you found them.',link:'https://www.incredibleindia.gov.in/'}];
export function MoodTiles({onChoose,active}:{onChoose?:(interest:string)=>void;active?:string}){return <div className="mood-grid">{moods.map(({name,interest,icon:Icon,tone})=>onChoose?<button key={name} className={`mood-tile ${tone}`} aria-pressed={active===interest} onClick={()=>onChoose(interest)}><Icon size={28} strokeWidth={1.5}/><span>{name}</span></button>:<Link key={name} className={`mood-tile ${tone}`} href={`/explore?interest=${interest}#destinations`}><Icon size={28} strokeWidth={1.5}/><span>{name}</span></Link>)}</div>;}
export function PopularSights(){return <section className="discovery-section"><div className="section-heading-row"><div><p className="eyebrow">A FEW ICONS, A LITTLE WONDER</p><h2 className="section-title">Places worth a detour</h2></div><Link className="text-link" href="/explore#destinations">All destinations <ArrowRight size={16}/></Link></div><div className="sight-grid">{sights.map(s=><Link className="sight-card" href={`/explore/${s.id}`} key={s.id}><ReferencePhoto sheet="places" rect={[s.x,737,325,322]} alt={s.name}/><div className="sight-copy"><span>{s.area}</span><h3>{s.name}</h3><ArrowRight size={20}/></div></Link>)}</div></section>;}
export default function DiscoveryHub({compact=false}:{compact?:boolean}){const [craft,setCraft]=useState('All'),[fact,setFact]=useState(0),[selected,setSelected]=useState<string|null>(null);const current=facts[fact];return <>
 <PopularSights/>
 <section className="editorial-banner"><div><p className="eyebrow">A DIFFERENT KIND OF SOUVENIR</p><h2>Bring home a story.</h2><p>Meet the makers behind India’s crafts, food and everyday traditions.</p><a className="btn-primary" href={compact?'/explore#local-craft':'#local-craft'}>Explore local crafts <ArrowRight size={16}/></a></div><ReferencePhoto sheet="crafts" rect={[1060,921,740,400]} alt="An artisan shaping clay on a pottery wheel"/></section>
 {!compact&&<><section className="discovery-section" id="local-craft"><div className="section-heading-row"><div><p className="eyebrow">ONE DISTRICT, MANY STORIES</p><h2 className="section-title">Made here. Remembered everywhere.</h2><p className="muted text-sm mt-2">Discover craft traditions and local produce.</p></div><a className="text-link" href="https://www.odop.gov.in/" target="_blank" rel="noreferrer">Official ODOP directory ↗</a></div><div className="craft-filters"><button className="chip" aria-pressed={craft==='All'} onClick={()=>setCraft('All')}>All</button>{craftKinds.map(({name,icon:Icon},i)=><button className={'chip craft-chip tone-'+i} key={name} aria-pressed={craft===name} onClick={()=>setCraft(name)}><Icon size={17}/>{name}</button>)}</div><div className="craft-grid">{crafts.filter(c=>craft==='All'||c.kind===craft).map(c=><article className="craft-card" key={c.name}><ReferencePhoto sheet="crafts" rect={[c.x,415,330,300]} alt={c.name}/><div><p className="eyebrow">{c.kind}</p><h3>{c.name}</h3><p className="text-sm muted">{c.area}</p><button className="text-link mt-3" onClick={()=>setSelected(selected===c.name?null:c.name)} aria-expanded={selected===c.name}>Discover the tradition <ArrowRight size={14}/></button>{selected===c.name&&<p className="mt-3 text-sm muted">{c.copy} These are editorial ideas, not verified sellers or official district designations.</p>}</div></article>)}</div></section>
 <section className="discovery-section india-notebook" id="india-notebook"><p className="eyebrow">THE INDIA NOTEBOOK</p><h2 className="section-title">A little context goes a long way.</h2><div className="craft-filters" role="group" aria-label="India notebook topics">{facts.map(({name,icon:Icon},i)=><button className="chip" aria-pressed={fact===i} onClick={()=>setFact(i)} key={name}><Icon size={17}/>{name}</button>)}</div><div className="notebook-feature"><div><span className="notebook-number">0{fact+1}</span><h3>{current.title}</h3><p>{current.copy}</p><a className="text-link" href={current.link} target="_blank" rel="noreferrer">Read on the official guide ↗</a></div><ReferencePhoto sheet="india" rect={[1056,416,735,410]} alt="Illustration of India's flag and the Red Fort"/></div></section></>}
 </>;}
