'use client';
import {useEffect} from 'react';
import {useForm} from 'react-hook-form';
import {zodResolver} from '@hookform/resolvers/zod';
import {z} from 'zod';
import {CATEGORIES,type Expense} from '@/lib/journal';
import {todayDate} from '@/lib/trip';
import {Button} from './ui/button';
import {Input} from './ui/input';
const schema=z.object({amount:z.string().regex(/^\d+(\.\d{1,2})?$/,'Enter an amount with up to 2 decimal places').refine(v=>Number(v)>0&&Number(v)<=10000000,'Amount must be above 0 and up to 1 crore'),category:z.enum(CATEGORIES),date:z.string().min(10),note:z.string().max(300),paidBy:z.string().min(1).max(80)});
export default function ExpenseForm({editing,onSave,onCancel}:{editing:Expense|null;onSave:(e:Expense)=>void;onCancel:()=>void}){const {register,reset,handleSubmit,formState:{errors}}=useForm<z.infer<typeof schema>>({resolver:zodResolver(schema),defaultValues:{amount:'',category:'Food',date:todayDate(),note:'',paidBy:'Traveller 1'}});useEffect(()=>{reset(editing?{amount:(editing.amountPaise/100).toFixed(2),category:editing.category,date:editing.date,note:editing.note,paidBy:editing.paidBy}:{amount:'',category:'Food',date:todayDate(),note:'',paidBy:'Traveller 1'});},[editing,reset]);return <form className="panel mt-6" onSubmit={handleSubmit(v=>{onSave({id:editing?.id||crypto.randomUUID(),amountPaise:Math.round(Number(v.amount)*100),category:v.category,date:v.date,note:v.note,paidBy:v.paidBy});reset({amount:'',category:'Food',date:todayDate(),note:'',paidBy:'Traveller 1'});})}><h2 className="text-xl font-bold">{editing?'Edit expense':'Record an expense'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><label><span className="label">Amount · INR</span><Input inputMode="decimal" placeholder="e.g. 450.50" {...register('amount')}/>{errors.amount&&<span className="text-xs text-red-700">{errors.amount.message}</span>}</label><label><span className="label">Category</span><select className="input" {...register('category')}>{CATEGORIES.map(c=><option key={c}>{c}</option>)}</select></label><label><span className="label">Payment date</span><Input type="date" {...register('date')}/></label><label><span className="label">Paid by</span><Input {...register('paidBy')}/></label><label className="sm:col-span-2"><span className="label">Note / what this covered</span><Input placeholder="Lunch, room advance, taxi…" {...register('note')}/></label></div><div className="mt-5 flex gap-3"><Button>{editing?'Save expense':'Add expense'}</Button>{editing&&<Button type="button" variant="outline" onClick={onCancel}>Cancel editing</Button>}</div></form>;}
