'use client';
import {rememberItinerary} from '@/lib/travel-store';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { MapPin, RefreshCw, Utensils, Hotel, Compass, BusFront } from 'lucide-react';
import type { Itinerary } from '@/lib/itinerary';
import type { TripForm } from '@/types/travel';
import type { NearbyResult } from '@/lib/nearby-types';
import { defaultTrip } from '@/lib/trip';
import PlaceRating,{readRatings} from './PlaceRating';
import destinations from '@/data/destinations.json';
export default function NearbyPanel({itinerary,initialKind='restaurant',day,onUpdate,cuisine}:{itinerary:Itinerary;initialKind?:string;day?:number;cuisine?:string;onUpdate?:(result:NearbyResult)=>void}){
 const [result,setResult]=useState(itinerary.nearby),[kind,setKind]=useState(initialKind),[radius,setRadius]=useState(itinerary.nearby?.radiusKm||3),[search,setSearch]=useState(''),[localOnly,setLocalOnly]=useState(false),[diet,setDiet]=useState('any'),[minRating,setMinRating]=useState(0),[ratings,setRatings]=useState<ReturnType<typeof readRatings>>({}),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{if(cuisine!==undefined){setSearch(cuisine);setKind('restaurant');}},[cuisine]);
 useEffect(()=>setResult(itinerary.nearby),[itinerary.nearby]);
 useEffect(()=>setKind(initialKind),[initialKind]);
 useEffect(()=>{const load=()=>setRatings(readRatings());load();window.addEventListener('travelsetu-ratings',load);return()=>window.removeEventListener('travelsetu-ratings',load);},[]);
 async function refresh(){setBusy(true);setMessage('');try{const stored=localStorage.getItem('travelsetu_trip');const trip:TripForm={...defaultTrip(),...(stored?JSON.parse(stored):{}),destination:itinerary.destination,from:itinerary.from,startDate:itinerary.startDate,endDate:itinerary.endDate,travellers:itinerary.travellers,budget:itinerary.budgetLimit||itinerary.estimatedCost,nearbyRadiusKm:radius};const response=await fetch('/api/nearby',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip,itinerary}),signal:AbortSignal.timeout(25000)});const data=await response.json();if(!response.ok)throw new Error(data.error);setResult(data);onUpdate?.(data);try{rememberItinerary({...itinerary,nearby:data});}catch{setMessage('Places loaded, but could not be saved in this browser.');}}catch{setMessage('Nearby search is unavailable. Try again shortly.');}finally{setBusy(false);}}
 const visible=useMemo(()=>result?.places.filter(p=>p.kind===kind&&(!day||!p.dayNumbers.length||p.dayNumbers.includes(day))&&(!search||[p.name,p.cuisine,p.nearStop].join(' ').toLowerCase().includes(search.toLowerCase()))&&(!localOnly||p.localMatch)&&(!minRating||(ratings[p.id]?.stars||0)>=minRating)&&(diet==='any'||diet==='vegan'&&['yes','only'].includes(p.vegan||'')||diet==='vegetarian'&&['yes','only'].includes(p.vegetarian||'')))||[],[result,kind,day,search,localOnly,minRating,ratings,diet]);
 const d=destinations.find(d=>d.name===itinerary.destination)!;
 return <section className="panel mt-6" id="nearby"><div className="flex flex-wrap justify-between gap-4"><div><p className="eyebrow">NEAR YOUR ROUTE</p><h2 className="mt-2 text-2xl font-bold">Around your {day?`Day ${day}`:'trip'} stops</h2><p className="mt-2 max-w-2xl text-sm muted">Find food, stays and experiences near your stops.</p></div><button className="btn-secondary h-fit" onClick={refresh} disabled={busy}><RefreshCw size={16} className={busy?'animate-spin':''}/>{busy?'Finding nearby places…':'Refresh nearby places'}</button></div>
 <div className="my-5 flex flex-wrap gap-2">{([['restaurant','Food & cafés',Utensils],['hotel','Hotels & homestays',Hotel],['experience','Local experiences',Compass],['transport','Buses, taxis & rentals',BusFront]] as const).map(([k,label,Icon])=><button key={k} className="chip" aria-pressed={kind===k} onClick={()=>{setKind(k);setDiet('any');}}><Icon size={15}/>{label}</button>)}</div>
 <details className="quiet-details"><summary>Search & filters</summary><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label><span className="label">Name, cuisine or neighbourhood</span><input className="input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Try a neighbourhood or cuisine"/></label><label><span className="label">Search radius · km</span><select className="input" value={radius} onChange={e=>setRadius(+e.target.value)}>{[1,2,3,5,10].map(n=><option key={n}>{n}</option>)}</select></label><label><span className="label">Your saved rating</span><select className="input" value={minRating} onChange={e=>setMinRating(+e.target.value)}><option value="0">Any / unrated</option><option value="3">3+ stars</option><option value="4">4+ stars</option><option value="5">5 stars</option></select></label>{kind==='restaurant'&&<label><span className="label">Mapped dietary option</span><select className="input" value={diet} onChange={e=>setDiet(e.target.value)}><option value="any">Any / confirm directly</option><option value="vegetarian">Vegetarian tag listed</option><option value="vegan">Vegan tag listed</option></select></label>}</div>
 {['restaurant','experience'].includes(kind)&&<label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={localOnly} onChange={e=>setLocalOnly(e.target.checked)}/> Regional cuisine / neighbourhood tags only</label>}
 </details>
 {radius!==result?.radiusKm&&result&&<p className="mt-3 text-sm text-blue-700">Press “Refresh nearby places” to search the new radius.</p>}
 <details className="mt-4 text-xs muted"><summary>Listing source & availability</summary><p className="mt-3">{result?.message||'Refresh to find mapped places around your plan. No venues are fabricated when the service is unavailable.'}{result&&<> Checked {new Date(result.checkedAt).toLocaleString('en-IN')}.</>}</p></details>{message&&<p role="status" className="mt-3 text-sm muted">{message}</p>}
 <div className="mt-5 grid gap-4 md:grid-cols-2">{visible.slice(0,16).map(p=><article key={p.id} className="rounded-2xl border border-slate-200 p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-bold">{p.name}</h3>{p.localMatch&&<span className="rounded-lg bg-emerald-50 px-2 py-1 text-xs font-bold text-emerald-800">Local-interest match</span>}</div><p className="mt-2 flex items-start gap-1 text-sm text-blue-700"><MapPin size={15} className="mt-1 shrink-0"/>{p.distanceKm.toFixed(1)} km from {p.nearStop}</p><details className="mt-3 text-sm"><summary>Details & reviews</summary><p className="mt-2 text-xs muted">Straight-line distance · {p.matchReason}</p>{p.cuisine&&<p className="mt-3 text-sm">Cuisine: {p.cuisine.replaceAll(';',', ')}</p>}{p.openingHours&&<p className="mt-2 text-xs muted">Listed hours: {p.openingHours} · verify for your date</p>}{p.phone&&<p className="mt-2 text-xs muted">Listed phone: {p.phone}</p>}<div className="mt-4 flex flex-wrap gap-3 text-sm font-bold"><Link className="text-blue-700" href={`/trip-map?lat=${p.latitude}&lng=${p.longitude}&name=${encodeURIComponent(p.name)}`}>Navigate in app →</Link><a href={p.sourceUrl} target="_blank" rel="noreferrer" className="text-blue-700">OpenStreetMap listing ↗</a>{p.kind==='hotel'&&<Link href={`/marketplace?tab=hotel&latitude=${p.latitude}&longitude=${p.longitude}&area=${encodeURIComponent(p.name)}&destination=${d.id}`}>Search stays in this area →</Link>}</div>{(p.kind==='hotel'||p.kind==='restaurant')&&<PlaceRating id={p.id} name={p.name} kind={p.kind} latitude={p.latitude} longitude={p.longitude}/>}</details></article>)}</div>
 {!visible.length&&<div className="rounded-2xl bg-slate-50 p-5 mt-5"><h3 className="font-bold">{result?'No matching listings were returned.':'Nearby places are ready to explore.'}</h3><p className="mt-2 text-sm muted">Try refreshing, increasing the radius, or clearing filters. Local ownership, accessibility and dietary options are never assumed from a name.</p></div>}{visible.length>16&&<p className="mt-3 text-sm muted">Showing 16 of {visible.length} matches. Narrow the name or cuisine filter to find more.</p>}
 </section>;
}
