'use client';
import {useEffect,useState} from 'react';
import {Star} from 'lucide-react';
import {z} from 'zod';
import {supabase} from '@/lib/supabase';
import {useTravelStore} from '@/lib/travel-store';
import {isDate} from '@/lib/trip-validation';
import {todayDate} from '@/lib/trip';
export const RATING_KEY='travelsetu_personal_ratings';
export type PersonalRating={stars:number;note:string;updatedAt:string;published?:boolean;visitedOn?:string};
const reviewSchema=z.object({stars:z.number().int().min(1).max(5),note:z.string().max(1200),visitedOn:z.string().refine(v=>!v||isDate(v),'Choose a valid visit date').optional(),published:z.boolean()});
function storageKey(){return RATING_KEY+':'+(useTravelStore.getState().userId||'guest');}
export function readRatings():Record<string,PersonalRating>{try{const r=JSON.parse(localStorage.getItem(storageKey())||(!useTravelStore.getState().userId?localStorage.getItem(RATING_KEY):null)||'{}');return r&&typeof r==='object'&&!Array.isArray(r)?r:{};}catch{return {};}}
export default function PlaceRating({id,name,kind='attraction',latitude,longitude,onChange}:{id:string;name:string;kind?:'attraction'|'restaurant'|'hotel'|'experience'|'transport';latitude?:number;longitude?:number;onChange?:()=>void}){
 const userId=useTravelStore(s=>s.userId),[rating,setRating]=useState<PersonalRating|null>(null),[note,setNote]=useState(''),[date,setDate]=useState(todayDate()),[published,setPublished]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[reviews,setReviews]=useState<{stars:number;review:string;visited_on:string;updated_at:string}[]>([]);
 async function loadPublic(){const c=supabase();if(!c)return;const {data,error}=await c.rpc('public_place_reviews',{target_place:id});if(!error)setReviews(data||[]);}
 useEffect(()=>{let active=true;const value=readRatings()[id];setRating(value||null);setNote(value?.note||'');setPublished(value?.published||false);setDate(value?.visitedOn||todayDate());setMessage('');const c=supabase();if(c){c.rpc('public_place_reviews',{target_place:id}).then(({data,error})=>{if(active&&!error)setReviews(data||[]);});if(userId)c.from('place_reviews').select('stars,review,visited_on,published,updated_at').eq('owner_id',userId).eq('place_id',id).maybeSingle().then(({data,error})=>{if(active&&!error&&data&&(!value||value.updatedAt<data.updated_at)){setRating({stars:data.stars,note:data.review,updatedAt:data.updated_at,published:data.published,visitedOn:data.visited_on});setNote(data.review);setPublished(data.published);setDate(data.visited_on||todayDate());}});}return()=>{active=false;};},[id,userId]);
 function localSave(stars:number){try{reviewSchema.parse({stars,note,visitedOn:date,published});if(date>todayDate()){setMessage('A visit date cannot be in the future.');return;}const next={stars,note:note.trim().slice(0,1200),updatedAt:new Date().toISOString(),published,visitedOn:date};const ratings=readRatings();ratings[id]=next;localStorage.setItem(storageKey(),JSON.stringify(ratings));setRating(next);setMessage('Saved on this device. Use “Save review to account” to sync.');onChange?.();window.dispatchEvent(new Event('travelsetu-ratings'));}catch{setMessage('Could not save this review locally.');}}
 async function saveCloud(){if(!rating)return;setBusy(true);try{const value=reviewSchema.parse({stars:rating.stars,note,visitedOn:date,published});const c=supabase();if(!c||!userId)throw new Error('Sign in to save this review permanently or publish it.');if(date>todayDate())throw new Error('A visit date cannot be in the future.');const {error}=await c.from('place_reviews').upsert({owner_id:userId,place_id:id,place_name:name.slice(0,200),kind,stars:value.stars,review:value.note,visited_on:date||null,published:value.published,updated_at:new Date().toISOString(),...(Number.isFinite(latitude)&&Number.isFinite(longitude)?{location:`SRID=4326;POINT(${longitude} ${latitude})`}:{})},{onConflict:'owner_id,place_id'});if(error)throw new Error('Could not save the review. Check your connection and database setup.');localSave(value.stars);await loadPublic();setMessage(published?'Review published. You can edit it or make it private here.':'Private review saved to your account.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function remove(){setBusy(true);try{const c=supabase();if(userId&&c){const {error}=await c.from('place_reviews').delete().eq('owner_id',userId).eq('place_id',id);if(error)throw new Error('Could not remove the saved review.');}const ratings=readRatings();delete ratings[id];localStorage.setItem(storageKey(),JSON.stringify(ratings));setRating(null);setNote('');setPublished(false);setMessage('Review removed.');await loadPublic();window.dispatchEvent(new Event('travelsetu-ratings'));onChange?.();}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const average=reviews.length?reviews.reduce((s,r)=>s+r.stars,0)/reviews.length:0;
 return <div className="mt-4 border-t border-slate-100 pt-4"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-bold">Your rating {rating?`${rating.stars}/5`:'· not rated'}</span><div className="flex" role="group" aria-label={`Your rating for ${name}`}>{[1,2,3,4,5].map(n=><button type="button" key={n} disabled={busy} aria-label={`Rate ${name} ${n} out of 5`} aria-pressed={rating?.stars===n} onClick={()=>localSave(n)} className="rounded p-1.5 text-amber-500"><Star size={19} fill={(rating?.stars||0)>=n?'currentColor':'none'}/></button>)}</div></div><details className="mt-2 text-xs muted"><summary className="cursor-pointer">Write or edit your visit review</summary><label className="mt-3 block">Visit date<input className="input mt-1" type="date" max={todayDate()} value={date} onChange={e=>setDate(e.target.value)}/></label><textarea aria-label={`Your review of ${name}`} className="input mt-3" maxLength={1200} value={note} onChange={e=>setNote(e.target.value)} placeholder="What did you enjoy? What should other travellers know?"/><label className="mt-3 flex gap-2"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/>Publish my rating and review when I save to my account</label><div className="mt-3 flex flex-wrap gap-3"><button type="button" disabled={!rating||busy} className="font-bold text-blue-700" onClick={saveCloud}>{busy?'Saving…':'Save review to account'}</button><button type="button" disabled={!rating} onClick={()=>localSave(rating!.stars)}>Save on device</button>{rating&&<button type="button" disabled={busy} onClick={remove}>Delete review</button>}</div><p className="mt-3">Public reviews are traveller opinions, not verified-stay ratings. Your identity and email are not displayed. Private reviews stay visible only to your account.</p></details><details className="mt-3 text-xs muted"><summary className="cursor-pointer">{reviews.length?`${average.toFixed(1)}/5 across ${reviews.length} recent public reviews`:'No public reviews loaded yet'}</summary><div className="mt-3 space-y-3">{reviews.slice(0,10).map((r,i)=><div key={i} className="rounded-xl bg-slate-50 p-3"><strong>{r.stars}/5 · Traveller review</strong><p className="mt-1 whitespace-pre-wrap">{r.review||'Rating only'}</p><span className="text-[10px]">Visit: {r.visited_on||'Not provided'}</span></div>)}</div></details>{message&&<p role="status" className="mt-2 text-xs muted">{message}</p>}</div>;
}
