'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Wallet,MapPin,Camera,Cloud,Download,CheckCircle2} from 'lucide-react';
import {useTravelStore} from '@/lib/travel-store';
import {analytics,CATEGORIES,type Expense} from '@/lib/journal';
import {formatINR} from '@/lib/trip';
import {saveCloudTrip,uploadPhoto,photoUrl} from '@/lib/cloud';
import {downloadBlob} from '@/lib/offline';
import BudgetCharts from './BudgetCharts';
import ExpenseForm from './ExpenseForm';
import PlaceRating from './PlaceRating';
import SharePanel from './SharePanel';
import TripDownloads from './TripDownloads';
import {Button} from './ui/button';
import {Card} from './ui/card';
export default function TripJournal({mode}:{mode:'budget'|'post-trip'}){
 const {records,userId,notice}=useTravelStore(),[selected,setSelected]=useState(''),[editing,setEditing]=useState<Expense|null>(null),[filter,setFilter]=useState('All'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[photo,setPhoto]=useState('');
 useEffect(()=>{useTravelStore.getState().hydrate();const s=useTravelStore.getState();try{const plan=JSON.parse(localStorage.getItem('travelsetu_itinerary')||'null');if(plan?.days&&!s.records.some(r=>r.itinerary.createdAt===plan.createdAt&&r.itinerary.startDate===plan.startDate&&r.itinerary.destination===plan.destination&&(!r.ownerId||r.ownerId===s.userId)))s.capture(plan);}catch{}},[]);
 const available=records.filter(r=>!r.ownerId||r.ownerId===userId),record=available.find(r=>r.id===selected)||available[0];
 async function action(fn:()=>Promise<unknown>,success:string){setBusy(true);setMessage('');try{await fn();setMessage(success);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 if(!record)return <main className="page-shell"><div className="container-page max-w-3xl"><p className="eyebrow">Every journey has a story</p><h1 className="page-title">{mode==='budget'?'Make every rupee count.':'Your journey, remembered.'}</h1><p className="mt-4 muted">Generate an itinerary to start your trip journal, track expenses and review the places you visit. Sign in to access trips saved on another device.</p><div className="mt-6 flex gap-3"><Link className="btn-primary" href="/plan-trip">Plan my trip</Link><Link className="btn-secondary" href="/account">My account</Link></div></div></main>;
 const data=analytics(record),plan=record.itinerary;const sights=Array.from(new Map([...plan.days,...(plan.baselineDays||[])].flatMap(d=>d.activities).filter(a=>a.placeId).map(a=>[a.placeId!,{id:a.placeId!,name:a.name,kind:(a.type==='food'?'restaurant':a.type==='stay'?'hotel':'attraction') as 'restaurant'|'hotel'|'attraction',latitude:a.latitude,longitude:a.longitude}])).values());
 const places=[...sights,...(plan.nearby?.places||[])];const shown=record.expenses.filter(e=>filter==='All'||e.category===filter);
 const patch=(value:Parameters<ReturnType<typeof useTravelStore.getState>['change']>[1])=>useTravelStore.getState().change(record.id,value);
 function csv(){const cell=(v:string|number)=>'"'+String(v).replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const rows=[['Date','Category','INR','Paid by','Note'],...record!.expenses.map(e=>[e.date,e.category,(e.amountPaise/100).toFixed(2),e.paidBy,e.note])];downloadBlob(new Blob(['\uFEFF'+rows.map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'TravelSetu-expenses.csv');}
 return <main className="page-shell"><div className="container-page"><div className="flex flex-wrap justify-between gap-5"><div><p className="eyebrow">{mode==='budget'?'Less guesswork. More discovery.':'The trip ends. The memories stay.'}</p><h1 className="page-title">{mode==='budget'?'Your budget, in view.':'Your travel chapter.'}</h1><p className="mt-3 muted">{plan.destination} · {plan.startDate} → {plan.endDate} · {plan.travellers} travellers</p></div><div className="flex flex-wrap items-center gap-3"><Link className="btn-secondary" href={mode==='budget'?'/post-trip':'/budget'}>{mode==='budget'?'Post-trip journal':'Budget analytics'}</Link><Link className="btn-secondary" href="/account">Account</Link></div></div>
 <section className="panel mt-6 flex flex-wrap items-end justify-between gap-4"><label className="min-w-0 flex-1"><span className="label">Choose a trip</span><select className="input" value={record.id} onChange={e=>{setSelected(e.target.value);setEditing(null);setPhoto('');setMessage('');}}>{available.map(r=><option value={r.id} key={r.id}>{r.itinerary.destination} · {r.itinerary.startDate} · {r.completed?'Completed':'In progress'}</option>)}</select></label><Button disabled={busy} onClick={()=>action(()=>saveCloudTrip(record),'Trip saved to your account.')}><Cloud size={16}/>{busy?'Working…':'Save to account'}</Button></section>
 <p className="mt-3 text-xs muted">{record.ownerId?record.pendingSync?'Changes saved on this device; account sync pending.':'Synced to your account.':'Device-only journal. Sign in and save once to enable account syncing.'} {notice}</p>{message&&<p role="status" className="notice mt-4">{message}</p>}
 <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[{label:'Group budget',value:formatINR(data.budget),icon:<Wallet/>},{label:'Recorded spending',value:formatINR(data.actual),icon:<Wallet/>},{label:data.remaining<0?'Over budget':'Budget remaining',value:formatINR(Math.abs(data.remaining)),icon:<Wallet/>},{label:'Places marked visited',value:String(data.visited),icon:<MapPin/>}].map(s=><Card key={s.label} className="p-6"><div className="flex items-center justify-between text-blue-700"><span className="text-xs font-bold uppercase tracking-wide">{s.label}</span>{s.icon}</div><strong className="mt-4 block text-3xl">{s.value}</strong></Card>)}</div>
 {mode==='budget'?<><BudgetCharts data={data}/><div className="notice mt-5">Recorded spending averages {formatINR(data.perPerson)} per traveller. Planned emergency reserve: {formatINR(data.reserve)}. Remaining after protecting that reserve: {formatINR(data.spendableRemaining)}. These are recorded payments; unpaid bookings and unrecorded costs are not included.</div><ExpenseForm editing={editing} onCancel={()=>setEditing(null)} onSave={e=>{try{useTravelStore.getState().addExpense(record.id,e);setEditing(null);setMessage('Expense saved.');}catch{setMessage('Expense could not be saved. Check the date and amount.');}}}/>
 <section className="panel mt-6"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">Your expense ledger</h2><div className="flex gap-3"><select className="input" aria-label="Filter expense category" value={filter} onChange={e=>setFilter(e.target.value)}>{['All',...CATEGORIES].map(c=><option key={c}>{c}</option>)}</select><Button variant="outline" onClick={csv}><Download size={16}/>CSV</Button></div></div><div className="mt-5 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b text-xs text-slate-500">{['Date','Category / note','Paid by','Amount','Actions'].map(t=><th className="p-3" key={t}>{t}</th>)}</tr></thead><tbody>{shown.map(e=><tr className="border-b" key={e.id}><td className="whitespace-nowrap p-3">{e.date}</td><td className="p-3"><strong>{e.category}</strong><p className="text-xs muted">{e.note}</p></td><td className="p-3">{e.paidBy}</td><td className="whitespace-nowrap p-3">{formatINR(e.amountPaise/100)}</td><td className="p-3"><div className="flex gap-3"><button className="font-bold text-blue-700" onClick={()=>setEditing(e)}>Edit</button><button className="text-red-700" onClick={()=>{patch({expenses:record.expenses.filter(x=>x.id!==e.id)});if(editing?.id===e.id)setEditing(null);setMessage('Expense removed.');}}>Delete</button></div></td></tr>)}</tbody></table>{!shown.length&&<p className="py-6 text-sm muted">No expenses in this view yet.</p>}</div></section></>:<>
 <section className="panel mt-6"><div className="flex flex-wrap items-center justify-between gap-4"><h2 className="text-xl font-bold">The story of this trip</h2><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={record.completed} onChange={e=>patch({completed:e.target.checked})}/><CheckCircle2 size={18}/>Trip completed</label></div><label className="mt-5 block text-sm font-bold">Your private notes<textarea className="input mt-2 min-h-32" value={record.reflection} maxLength={5000} onChange={e=>patch({reflection:e.target.value})} placeholder="Best meal? A place you would return to? What would you do differently?"/></label><p className="mt-2 text-xs muted">Notes, exact dates, photos and itemised expenses stay out of social recaps.</p></section>
 <details className="quiet-details mt-8"><summary>Visited places & reviews</summary><section><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-2xl font-bold">Where you went. What you loved.</h2><p className="mt-2 text-sm muted">Mark places you actually visited, then add a rating and review. Public posting is optional.</p></div><Link href="/nearby" className="btn-secondary">Find more nearby places</Link></div><div className="mt-5 grid items-start gap-4 md:grid-cols-2 lg:grid-cols-3">{places.map(p=><article key={p.id} className="panel"><span className="eyebrow">{p.kind}</span><h3 className="mt-2 text-lg font-bold">{p.name}</h3><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={record.visited.includes(p.id)} onChange={e=>patch({visited:e.target.checked?[...new Set([...record.visited,p.id])]:record.visited.filter(v=>v!==p.id)})}/>I visited this place</label>{record.visited.includes(p.id)&&<PlaceRating id={p.id} name={p.name} kind={p.kind} latitude={p.latitude} longitude={p.longitude}/>}</article>)}</div>{!places.length&&<p className="notice mt-4">No named places are saved yet. Open a generated itinerary and refresh nearby listings.</p>}</section></details>
 <details className="quiet-details mt-6"><summary>Private photo album</summary><section><div className="flex items-center gap-2"><Camera/><h2 className="text-xl font-bold">A private photo album</h2></div><p className="mt-2 text-sm muted">Account required. JPG, PNG or WebP up to 5 MB each; 20 photos per trip. Stored privately with temporary viewing links.</p><input aria-label="Upload private trip photo" className="mt-4 block max-w-full text-sm" disabled={busy||record.photos.length>=20} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)action(()=>uploadPhoto(record,file),'Photo saved privately.');e.target.value='';}}/><div className="mt-4 flex flex-wrap gap-2">{record.photos.map(p=><Button key={p.path} disabled={busy} variant="outline" onClick={()=>action(async()=>setPhoto(await photoUrl(p.path)),'Photo link is valid for 10 minutes.')}>{p.name}</Button>)}</div>{photo&&<img src={photo} alt="Selected private trip memory" className="mt-5 max-h-96 rounded-xl object-contain"/>}</section></details>
 <SharePanel record={record}/></>}
 <details className="quiet-details mt-6"><summary>Backups & offline downloads</summary><section><h2 className="text-xl font-bold">Keep a complete private backup</h2><p className="mt-2 text-sm muted">Includes your journal, expenses and itinerary. Keep it private. If account sync reports a conflict, download a backup before resolving it.</p><div className="mt-4 flex flex-wrap gap-3"><Button variant="outline" onClick={()=>downloadBlob(new Blob([JSON.stringify(record,null,2)],{type:"application/json"}),"TravelSetu-private-journal.json")}>Download journal JSON</Button><Button variant="outline" onClick={()=>{const copy={...record,id:crypto.randomUUID(),ownerId:undefined,cloudVersion:undefined,pendingSync:true,updatedAt:new Date().toISOString()};useTravelStore.getState().merge([copy]);setSelected(copy.id);setMessage("Created a separate device copy. Save it to your account to preserve both versions.");}}>Keep as a separate trip copy</Button></div></section><TripDownloads plan={plan}/></details></div></main>;
}
