'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {CloudSun,Sun,Cloud,CloudRain,CloudSnow,CloudLightning,Wind,Droplets,CalendarDays,RefreshCw,ArrowRight,ArrowUp,Clock3} from 'lucide-react';
import destinations from '@/data/destinations.json';
import {todayDate,dateAt} from '@/lib/trip';
import type {WeatherResponse} from '@/lib/weather';
import {compassDirection} from '@/lib/weather-dashboard';
export function SkyIcon({code,size=27}:{code:number|null|undefined;size?:number}){const Icon=code===null||code===undefined?CloudSun:code>=95?CloudLightning:[71,73,75,77,85,86].includes(code)?CloudSnow:code>=51?CloudRain:code>=3?Cloud:code===2?CloudSun:Sun;return <Icon size={size} strokeWidth={1.5}/>;}
const value=(n:number|null|undefined,suffix='')=>n===null||n===undefined?'—':Math.round(n)+suffix;
export default function WeatherDashboard({destination,compact=false}:{destination:string;compact?:boolean}){
 const [data,setData]=useState<WeatherResponse|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0),[day,setDay]=useState('');
 useEffect(()=>{let active=true;const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),18000);setData(null);setBusy(true);setError('');setDay('');fetch('/api/weather',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination,startDate:todayDate(),endDate:dateAt(todayDate(),9),dashboard:true}),signal:controller.signal}).then(async r=>{const body=await r.json();if(!r.ok)throw new Error(body.error);if(!active)return;setData(body);setDay(body.daily?.[0]?.date||'');}).catch(e=>{if(!active)return;if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Forecast unavailable.');else setError('The forecast request timed out. Try refreshing.');}).finally(()=>{clearTimeout(timeout);if(active)setBusy(false);});return()=>{active=false;clearTimeout(timeout);controller.abort();};},[destination,reload]);
 const current=data?.skyCurrent,daily=data?.daily||[],selected=daily.find(d=>d.date===day)||daily[0],air=data?.airQuality,loc=destinations.find(d=>d.name===destination)!;
 const low=Math.min(...daily.map(d=>d.minTemperature)),high=Math.max(...daily.map(d=>d.maxTemperature));
 const aq=air?.usAqi,wind=current?.windDirection;
 const heading=<div className="sky-heading"><div><span className="sky-label"><CloudSun size={14}/> {compact?'WEATHER ALONG THE WAY':'YOUR WINDOW TO THE WEATHER'}</span><h2>{destination}</h2></div><button className="sky-refresh" aria-label="Refresh weather" onClick={()=>setReload(n=>n+1)} disabled={busy}><RefreshCw size={17} className={busy?'animate-spin':''}/></button></div>;
 if(compact)return <section className="sky-dashboard sky-compact">{heading}<div className="sky-now"><div><strong>{value(current?.temperature,'°')}</strong><p>{busy?'Checking the skies…':current?.description||'Current weather unavailable'}</p></div><SkyIcon code={current?.weatherCode} size={58}/></div><div className="sky-small-stats"><span><Droplets size={15}/>{value(selected?.rainProbability,'%')} rain chance</span><span><Wind size={15}/>{value(current?.windSpeed,' km/h')}</span></div><div className="sky-mini-days">{daily.slice(0,4).map(d=><div key={d.date}><small>{new Date(d.date+'T12:00:00').toLocaleDateString('en-IN',{weekday:'short'})}</small><SkyIcon code={d.weatherCode} size={20}/><strong>{value(d.maxTemperature,'°')}</strong></div>)}</div>{error&&<p role="status" className="sky-note">{error}</p>}<Link className="sky-link" href={`/weather?destination=${encodeURIComponent(destination)}`}>Open full forecast <ArrowRight size={15}/></Link><p className="sky-note">Open-Meteo · {data?.fetchedAt?new Date(data.fetchedAt).toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'}):'No data loaded'} · IST</p></section>;
 return <section className="sky-dashboard">{heading}<div className="sky-hero"><div><span className="sky-label">CURRENT MODEL CONDITIONS</span><div className="sky-temperature">{value(current?.temperature,'°')}</div><h3>{busy?'A look at the skies…':current?.description||'Current weather unavailable'}</h3><p>Feels like {value(current?.feelsLike,'°')} <span>·</span> H:{value(daily[0]?.maxTemperature,'°')} L:{value(daily[0]?.minTemperature,'°')}</p></div><div className="sky-hero-art"><SkyIcon code={current?.weatherCode} size={136}/><span>{data?.skyCurrent?.time?new Date(data.skyCurrent.time+'+05:30').toLocaleTimeString('en-IN',{hour:'2-digit',minute:'2-digit',timeZone:'Asia/Kolkata'})+' IST':'Waiting for a usable observation'}</span></div></div>
 {error&&<p className="sky-notice" role="alert">{error}<button onClick={()=>{setBusy(false);setReload(n=>n+1);}}>Try again</button></p>}
 <section className="sky-panel hourly-panel"><h3 className="sky-label"><Clock3 size={15}/> NEXT 24 HOURS</h3><div className="hourly-strip">{data?.hourly?.length?data.hourly.map(h=><div key={h.time}><span>{h.time.slice(11,16)}</span><SkyIcon code={h.weatherCode}/><strong>{value(h.temperature,'°')}</strong><small>{value(h.rainProbability,'%')}</small></div>):<p className="sky-note">{busy?'Loading hourly forecast…':'No hourly forecast available. Missing values are not replaced with demo weather.'}</p>}</div></section>
 <div className="sky-grid"><section className="sky-panel daily-panel"><h3 className="sky-label"><CalendarDays size={15}/> 10-DAY FORECAST</h3><div className="daily-list">{daily.map((d,i)=><button key={d.date} aria-pressed={selected?.date===d.date} onClick={()=>setDay(d.date)}><span>{i===0&&d.date===todayDate()?'Today':new Date(d.date+'T12:00:00').toLocaleDateString('en-IN',{weekday:'short'})}</span><span className="daily-icon"><SkyIcon code={d.weatherCode} size={22}/><small>{value(d.rainProbability,'%')}</small></span><span className="sky-low">{value(d.minTemperature,'°')}</span><span className="temperature-track"><i style={{left:`${(d.minTemperature-low)/Math.max(1,high-low)*100}%`,width:`${Math.max(5,(d.maxTemperature-d.minTemperature)/Math.max(1,high-low)*100)}%`}}/></span><strong>{value(d.maxTemperature,'°')}</strong></button>)}{!daily.length&&<p className="sky-note">{busy?'Loading the days ahead…':'Forecast unavailable for these dates.'}</p>}</div></section>
 <section className="sky-panel precipitation-panel"><div className="flex justify-between gap-3"><h3 className="sky-label"><Droplets size={15}/> PRECIPITATION</h3><strong>{value(selected?.precipitation,' mm')}</strong></div><iframe loading="lazy" title={`Map of the forecast location in ${destination}`} src={`https://www.openstreetmap.org/export/embed.html?bbox=${loc.longitude-.15}%2C${loc.latitude-.12}%2C${loc.longitude+.15}%2C${loc.latitude+.12}&layer=mapnik&marker=${loc.latitude}%2C${loc.longitude}`}/><p className="sky-note">{selected?.date||'Selected day'} · point forecast, not a radar layer. Map © OpenStreetMap.</p></section>
 <section className="sky-panel air-panel"><h3 className="sky-label"><Wind size={15}/> AIR QUALITY · US AQI</h3><div className="air-value">{value(aq)}</div><h4>{air?.label||'Air quality unavailable'}</h4><div className="aqi-scale">{aq!==undefined&&<i style={{left:`${Math.min(98,aq/500*100)}%`}}/>}</div><div className="flex justify-between text-xs"><span>Good</span><span>Hazardous</span></div><p className="sky-note">PM2.5 {air?.pm25??'—'} µg/m³ · PM10 {air?.pm10??'—'} µg/m³</p><p className="sky-note">{air?'Model estimate · Open-Meteo / CAMS. US AQI, not India’s NAQI.':'No air-quality values have been assumed.'}</p></section>
 <section className="sky-panel wind-panel"><h3 className="sky-label"><Wind size={15}/> WIND</h3><div className="wind-layout"><dl><div><dt>Wind</dt><dd>{value(current?.windSpeed,' km/h')}</dd></div><div><dt>Gusts</dt><dd>{value(current?.windGusts,' km/h')}</dd></div><div><dt>Direction</dt><dd>{value(wind,'°')} {compassDirection(wind??null)}</dd></div></dl><div className="wind-compass"><span>N</span><span>E</span><span>S</span><span>W</span><div className="compass-needle" style={{transform:`rotate(${wind??0}deg)`,opacity:wind===null||wind===undefined?0.25:1}}><ArrowUp size={60} fill="currentColor" strokeWidth={1}/></div></div></div><p className="sky-note">Direction the wind comes from · humidity {value(current?.humidity,'%')}</p></section></div>
 {selected&&<details className="sky-panel sky-day-detail"><summary>{new Date(selected.date+'T12:00:00').toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'short'})} · {selected.description}<span>{selected.risk==='AT RISK'?'Review outdoor plans':selected.risk==='CAUTION'?'Keep plans flexible':'No forecast trigger'}</span></summary><p className="sky-note">{selected.reason}</p></details>}
 <p className="sky-note sky-attribution"><a href="https://open-meteo.com/" target="_blank" rel="noreferrer">Weather: Open-Meteo</a> · <a href="https://atmosphere.copernicus.eu/" target="_blank" rel="noreferrer">Air quality: CAMS</a> · IST · {data?.fetchedAt?'Updated '+new Date(data.fetchedAt).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'}):'No live data loaded'}. Forecasts are not official safety warnings.</p></section>;
}
