const ts=require('typescript'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
const root=path.resolve(__dirname,'..');const originalResolve=Module._resolveFilename;
Module._resolveFilename=function(request,parent,...args){if(request.startsWith('@/'))request=path.join(root,request.slice(2));return originalResolve.call(this,request,parent,...args);};
require.extensions['.ts']=function(module,file){const text=fs.readFileSync(file,'utf8');const out=ts.transpileModule(text,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,resolveJsonModule:true}});module._compile(out.outputText,file);};
const test=require('node:test'),assert=require('node:assert/strict');
const {DEMO_TRIP,getTripDuration}=require('../lib/trip.ts');
const {parseTrip,minutes}=require('../lib/trip-validation.ts');
const {buildDemoItinerary,enrichItinerary,recalculateItinerary}=require('../lib/itinerary.ts');
const {parseSearch,demoOffers}=require('../lib/booking/catalog.ts');
const {hotelPayload,hotelBookingPayload,searchHotels,searchTransfers}=require('../lib/booking/hotelbeds.ts');
const {signOffer,readOffer}=require('../lib/booking/tokens.ts');
const {parseOsmElements}=require('../lib/map.ts');
const destinations=require('../data/destinations.json'),places=require('../data/places.json');
const trip=(overrides={})=>({...DEMO_TRIP,startDate:'2026-10-15',endDate:'2026-10-18',...overrides});
const query=(overrides={})=>parseSearch({kind:'hotel',mode:'demo',destinationId:'jaipur',from:'Delhi',checkIn:'2026-10-15',checkOut:'2026-10-18',rooms:2,adults:2,childrenAges:[],pickupTime:'10:00',...overrides});
test('dates include the departure day and reject malformed dates and impossible groups',()=>{assert.equal(getTripDuration('2026-10-15','2026-10-15'),1);assert.equal(getTripDuration('2026-10-15','2026-10-18'),4);assert.throws(()=>parseTrip(trip({startDate:'2026-02-30'})));assert.throws(()=>parseTrip(trip({endDate:'2026-10-14'})));assert.throws(()=>parseTrip(trip({children:3})));assert.throws(()=>parseTrip(trip({travellers:1.5})));});
test('all 37 destinations have local stops, no repeated named sights, valid schedules and consistent group totals',()=>{for(const d of destinations){const t=parseTrip(trip({destination:d.name})),plan=buildDemoItinerary(t,d);assert.equal(plan.days.length,4);assert.equal(plan.days.at(-1).date,t.endDate);const ids=new Set();for(const day of plan.days){let end=0;for(const a of day.activities){assert.ok(minutes(a.time)>=end,`${d.name}: overlapping ${a.name}`);end=minutes(a.time)+a.durationMinutes;assert.ok(end<=1440);assert.ok(a.estimatedCost>=0);if(a.placeId){assert.ok(!ids.has(a.placeId));ids.add(a.placeId);assert.equal(places.find(p=>p.id===a.placeId).destinationId,d.id);}}assert.equal(day.estimatedCost,day.activities.reduce((sum,a)=>sum+a.estimatedCost,0)+(day.lodgingCost||0));}assert.equal(plan.estimatedCost,plan.days.reduce((sum,d)=>sum+d.estimatedCost,0)+plan.budgetBreakdown.intercityTransport+plan.budgetBreakdown.reserve);}});
test('budgets are not capped and hotel costs scale with nights and room count',()=>{const t=trip({budget:1000}),p=buildDemoItinerary(t);assert.ok(p.estimatedCost>1000);assert.equal(buildDemoItinerary(trip({roomCount:2})).budgetBreakdown.stay,2*buildDemoItinerary(trip({roomCount:1})).budgetBreakdown.stay);assert.equal(buildDemoItinerary(trip({budgetScope:'at-destination'})).budgetBreakdown.intercityTransport,0);});
test('walking limits and high-altitude rest affect actual activities',()=>{assert.ok(buildDemoItinerary(trip({walkingLimitKm:0})).days.every(d=>!d.activities.some(a=>a.type==='activity')));const leh=buildDemoItinerary(trip({destination:'Leh'}));assert.ok(leh.days.slice(0,2).every(d=>!d.activities.some(a=>a.type==='activity')));});
test('early departure and same-day trips fit their available hours',()=>{const early=buildDemoItinerary(trip({departureTime:'02:00'}));const last=early.days.at(-1).activities.at(-1);assert.equal(minutes(last.time)+last.durationMinutes,120);const same=buildDemoItinerary(trip({endDate:'2026-10-15',arrivalTime:'10:00',departureTime:'14:00'}));assert.equal(same.days.length,1);assert.equal(same.budgetBreakdown.stay,0);for(const a of same.days[0].activities)assert.ok(minutes(a.time)+a.durationMinutes<=840);});
test('Gemini enrichment cannot change times, places, dates or totals',()=>{const seed=buildDemoItinerary(trip()),input={estimatedCost:1,tripSummary:'New summary',days:seed.days.map(d=>({...d,activityNotes:d.activities.map(a=>({...a,description:'Detailed note',estimatedCost:0,time:'00:00',latitude:0}))})),packingSuggestions:['Shoes'],travelTips:['Check hours']};const result=enrichItinerary(seed,input);assert.equal(result.estimatedCost,seed.estimatedCost);assert.equal(result.days[0].activities[0].time,seed.days[0].activities[0].time);assert.throws(()=>enrichItinerary(seed,{days:[]}));});
test('sample hotel totals use nights and rooms; vehicles enforce capacity',()=>{const q=query(),offers=demoOffers(q);assert.equal(offers.length,8);const one=demoOffers(query({rooms:1}));assert.equal(offers[0].price,one[0].price*2);const cars=demoOffers(query({kind:'vehicle',adults:7,rooms:1}));assert.ok(cars.every(c=>c.capacity>=7));assert.throws(()=>query({checkOut:'2026-10-15'}));});
test('signed quote rejects tampering',()=>{const offer=demoOffers(query())[0],token=signOffer(offer,'quote');assert.equal(readOffer(token).offer.price,offer.price);const [payload,sig]=token.split('.');const data=JSON.parse(Buffer.from(payload,'base64url'));data.offer.price=1;assert.throws(()=>readOffer(Buffer.from(JSON.stringify(data)).toString('base64url')+'.'+sig));});
test('Hotelbeds occupancy and guest payload matches room counts',()=>{const q=query({childrenAges:[7]}),payload=hotelPayload(q);assert.deepEqual(payload.occupancies[0],{rooms:2,adults:2,children:1,paxes:[{type:'CH',age:7}]});const offer={...demoOffers(q)[0],rateKey:'fixture'};const contact={name:'Test',surname:'Holder',guests:Array.from({length:6},()=>({name:'Test',surname:'Guest'}))};const body=hotelBookingPayload(offer,contact,'reference');assert.equal(body.rooms[0].paxes.length,6);assert.equal(body.rooms[0].paxes.filter(p=>p.type==='CH').length,2);assert.equal(body.tolerance,0);});
test('supplier adapters preserve currency, empty results and transfer capacity with mocked HTTP',async()=>{process.env.HOTELBEDS_HOTEL_API_KEY='fixture';process.env.HOTELBEDS_HOTEL_SECRET='fixture';process.env.HOTELBEDS_TRANSFER_API_KEY='fixture';process.env.HOTELBEDS_TRANSFER_SECRET='fixture';const q=query({mode:'test'});let called;const fake=async(url,init)=>{called={url,body:JSON.parse(init.body),headers:init.headers};return new Response(JSON.stringify({hotels:{hotels:[{code:12,name:'Test Hotel',currency:'EUR',rooms:[{code:'DBL',name:'Double',rates:[{rateKey:'key',rateType:'BOOKABLE',net:'240',rooms:2,adults:2,children:0}]}]}]}}),{status:200});};const hotels=await searchHotels(q,fake);assert.equal(hotels[0].currency,'EUR');assert.equal(hotels[0].price,240);assert.ok(called.url.startsWith('https://api.test.hotelbeds.com/'));assert.equal(called.headers['X-Signature'].length,64);assert.deepEqual(await searchHotels(q,async()=>new Response('{"hotels":{"hotels":[]}}')),[]);let transferUrl;const tq=query({kind:'vehicle',mode:'test',adults:2,rooms:1,pickupAirport:'JAI',dropoffHotel:'12'});const transfers=await searchTransfers(tq,async(url)=>{transferUrl=url;return new Response(JSON.stringify({services:[{id:1,rateKey:'key',vehicle:{name:'Sedan'},maxPaxCapacity:4,price:{totalAmount:60,currencyId:'EUR'}}]}));});assert.equal(transfers[0].currency,'EUR');assert.ok(transferUrl.includes('/from/IATA/JAI/to/ATLAS/12/'));delete process.env.HOTELBEDS_HOTEL_API_KEY;delete process.env.HOTELBEDS_HOTEL_SECRET;delete process.env.HOTELBEDS_TRANSFER_API_KEY;delete process.env.HOTELBEDS_TRANSFER_SECRET;});
test('map does not manufacture coordinates or service records',()=>{assert.deepEqual(parseOsmElements([{id:1,type:'node',tags:{amenity:'hospital'}}]),[]);const p=parseOsmElements([{id:2,type:'node',lat:26.912,lon:75.787,tags:{amenity:'pharmacy',name:'Test listing',wheelchair:'yes'}}]);assert.equal(p[0].source,'openstreetmap');assert.equal(p[0].category,'pharmacy');assert.equal(p[0].wheelchair,'yes');});
test('booking endpoint only confirms reviewed quotes and reuses the same confirmation',async()=>{const endpoint=require('../app/api/bookings/route.ts');const tmp=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'travelsetu-test-'));const before=process.cwd();process.chdir(tmp);try{const call=async b=>{const r=await endpoint.POST(new Request('http://localhost/api/bookings',{method:'POST',headers:{'Content-Type':'application/json',origin:'http://localhost'},body:JSON.stringify(b)}));return {status:r.status,data:await r.json()};};const search=await call({action:'search',query:query()});assert.equal(search.status,200);const offer=search.data.offers[0];assert.equal((await call({action:'confirm',token:offer.token,acceptTerms:true})).status,400);const quoted=await call({action:'quote',token:offer.token});const b={action:'confirm',token:quoted.data.offer.token,acceptTerms:true};const first=await call(b),again=await call(b);assert.equal(first.status,200);assert.equal(first.data.receipt.reference,again.data.receipt.reference);assert.equal(first.data.receipt.mode,'demo');assert.equal(again.data.repeated,true);}finally{process.chdir(before);fs.rmSync(tmp,{recursive:true,force:true});}});

const {todayDate,defaultTrip,currentDraft,dateAt}=require('../lib/trip.ts');
const {buildDailyWeather,classifyWeatherRisk,getWeather}=require('../lib/weather.ts');
const {adaptItinerary}=require('../lib/conditions/adapt.ts');
const {parseTraffic,parseDisasters,getConditions}=require('../lib/conditions/providers.ts');
const {rankNearby,attachNearby}=require('../lib/nearby.ts');
const checkNow=new Date('2026-10-14T04:30:00Z');
const cleanConditions=()=>({checkedAt:checkNow.toISOString(),weather:{source:'forecast',daily:[],fetchedAt:checkNow.toISOString(),fallback:false,latitude:32.24,longitude:77.189,location:'Manali',timezone:'Asia/Kolkata'},traffic:{provider:'TomTom',status:'available',checkedAt:checkNow.toISOString(),message:'Fixture'},disasters:{provider:'GDACS',status:'partial',checkedAt:checkNow.toISOString(),message:'Fixture'},alerts:[],legs:[]});
const severeDay=date=>({date,minTemperature:18,maxTemperature:28,rainProbability:95,precipitation:45,maxWindSpeed:18,maxWindGusts:24,humidity:80,weatherCode:65,description:'Heavy rain',risk:'AT RISK',reason:'Heavy rain forecast; exposed activities paused.'});
const assertSchedule=p=>{for(const day of p.days){let end=0;for(const a of day.activities){assert.ok(minutes(a.time)>=end,`Overlap: ${day.date} ${a.name}`);end=minutes(a.time)+a.durationMinutes;assert.equal(minutes(a.endTime),end);assert.ok(end<=1440);}assert.equal(day.estimatedCost,day.activities.reduce((s,a)=>s+a.estimatedCost,0)+(day.lodgingCost||0));}};
test('today defaults cross IST midnight correctly and preserve chosen future dates',()=>{assert.equal(todayDate(new Date('2026-09-08T18:29:00Z')),'2026-09-08');assert.equal(todayDate(new Date('2026-09-08T18:30:00Z')),'2026-09-09');const d=defaultTrip(new Date('2026-09-08T18:30:00Z'));assert.equal(d.startDate,'2026-09-09');assert.equal(d.endDate,'2026-09-13');assert.equal(currentDraft(trip(),checkNow).startDate,'2026-10-15');const moved=currentDraft(trip({startDate:'2026-10-01',endDate:'2026-10-04'}),checkNow);assert.equal(moved.startDate,'2026-10-14');assert.equal(getTripDuration(moved.startDate,moved.endDate),4);});
test('forecast values are joined on provider dates, and missing values never become zero-weather days',()=>{const raw={daily:{time:['2026-10-14','2026-10-15','2026-10-16'],temperature_2m_min:[5,15,16],temperature_2m_max:[9,25,null],precipitation_probability_max:[99,20,20],precipitation_sum:[60,0,1],wind_speed_10m_max:[70,10,11],wind_gusts_10m_max:[90,15,15],weather_code:[95,0,1]}};const days=buildDailyWeather(raw,['2026-10-15','2026-10-16','2026-10-17']);assert.equal(days.length,1);assert.equal(days[0].date,'2026-10-15');assert.equal(days[0].rainProbability,20);assert.equal(days[0].risk,'SAFE');});
test('rain probability alone is not a severe weather trigger',()=>{assert.equal(classifyWeatherRisk({rainProbability:98,windSpeed:10,temperature:24,precipitation:1,weatherCode:61}).risk,'CAUTION');assert.equal(classifyWeatherRisk({rainProbability:50,windSpeed:10,temperature:24,precipitation:40,weatherCode:65}).risk,'AT RISK');assert.equal(classifyWeatherRisk({rainProbability:10,windSpeed:10,temperature:24,weatherCode:95}).risk,'AT RISK');});
test('weather outages return unassessed dates with no simulated forecast',async()=>{const dates=[todayDate(),dateAt(todayDate(),1)];const result=await getWeather(32.24,77.189,dates,'Manali',async()=>{throw new Error('Offline');});assert.equal(result.source,'unavailable');assert.deepEqual(result.daily,[]);assert.deepEqual(result.missingDates,dates);});
test('local preference changes sight priority and dietary suggestions',()=>{const local=buildDemoItinerary(trip({destination:'Manali',experienceMode:'local'}));const highlights=buildDemoItinerary(trip({destination:'Manali',experienceMode:'highlights'}));const first=p=>p.days.flatMap(d=>d.activities).find(a=>a.type==='activity');assert.match(first(local).name,/Old Manali|Vashisht/);assert.notEqual(first(local).name,first(highlights).name);assert.ok(local.days.flatMap(d=>d.activities).some(a=>a.localExperience));const {foodIdeas}=require('../lib/local.ts');assert.doesNotMatch(foodIdeas({localFood:['Goan fish curry','Poi bread']},trip({foodPreference:'Vegetarian'})),/fish/);});
test('severe weather changes only the matching day and preserves departure',()=>{const t=trip(),seed=buildDemoItinerary(t),c=cleanConditions();c.weather.daily=[severeDay('2026-10-16')];const changed=adaptItinerary(seed,t,c,{now:checkNow});assertSchedule(changed);assert.deepEqual(changed.days[0].activities,seed.days[0].activities);assert.ok(changed.changes.every(x=>x.date==='2026-10-16'));assert.ok(changed.days[1].activities.every(a=>a.type!=='activity'||a.indoor));assert.equal(changed.days.at(-1).activities.at(-1).time,seed.days.at(-1).activities.at(-1).time);});
test('review mode gives suggestions without altering the plan',()=>{const t=trip(),seed=buildDemoItinerary(t),c=cleanConditions();c.weather.daily=[severeDay('2026-10-16')];const p=adaptItinerary(seed,t,c,{now:checkNow,apply:false});assert.deepEqual(p.days,seed.days);assert.ok(p.changes.length);assert.equal(p.changesApplied,false);});
test('traffic padding is idempotent and cannot push departure late',()=>{const t=trip(),seed=buildDemoItinerary(t),c=cleanConditions();const transfer=seed.days[0].activities.find(a=>a.type==='transport'&&a.distanceKm!==undefined);assert.ok(transfer);c.legs=[{day:1,activityId:transfer.id,minutes:transfer.durationMinutes+100,distanceKm:15,delayMinutes:100,source:'prediction'}];const one=adaptItinerary(seed,t,c,{now:checkNow}),two=adaptItinerary(one,t,c,{now:checkNow});assertSchedule(one);assertSchedule(two);assert.deepEqual(two.days,one.days);assert.equal(two.estimatedCost,one.estimatedCost);assert.ok(one.changes.some(c=>c.source==='TomTom'));});
test('missing or stale data cannot generate new hazard adjustments or reverse an unverified pause',()=>{const t=trip(),seed=buildDemoItinerary(t),c=cleanConditions();c.weather.source='unavailable';assert.deepEqual(adaptItinerary(seed,t,c,{now:checkNow}).days.map(d=>d.activities),seed.days.map(d=>d.activities));c.weather.source='forecast';c.weather.daily=[severeDay('2026-10-16')];c.checkedAt='2026-10-01T00:00:00Z';assert.deepEqual(adaptItinerary(seed,t,c,{now:checkNow}).days,seed.days);c.checkedAt=checkNow.toISOString();const paused=adaptItinerary(seed,t,c,{now:checkNow});c.weather.source='unavailable';c.weather.daily=[];const unknown=adaptItinerary(paused,t,c,{now:checkNow});assert.ok(unknown.days[1].activities.every(a=>a.type!=='activity'||a.indoor));});
test('regional and road reports require valid coordinates and active timestamps',()=>{const now=new Date('2026-10-14T10:00:00Z'),centre={latitude:32.24,longitude:77.189};const feature={geometry:{type:'Point',coordinates:[77.189,32.24]},properties:{eventid:1,eventtype:'FL',alertlevel:'Red',todate:'2026-10-14T00:00:00Z',name:'Fixture flood'}};assert.equal(parseDisasters({features:[feature]},centre,now).length,1);assert.equal(parseDisasters({features:[{...feature,properties:{...feature.properties,todate:'2026-09-01'}}]},centre,now).length,0);assert.equal(parseDisasters({features:[{...feature,geometry:{type:'Point',coordinates:[0,0]}}]},centre,now).length,0);assert.equal(parseTraffic({incidents:[{geometry:feature.geometry,properties:{id:'x',iconCategory:8,endTime:'2026-10-13T00:00:00Z'}}]},now).length,0);assert.throws(()=>parseTraffic({unexpected:true},now));});
test('nearby listings must have real coordinates and lie within a planned stop radius',()=>{const t=trip({experienceMode:'local',nearbyRadiusKm:1}),plan=buildDemoItinerary(t),sight=plan.days.flatMap(d=>d.activities).find(a=>a.latitude!==undefined);const fixture=[{type:'node',id:1,lat:sight.latitude,lon:sight.longitude,tags:{name:'Fixture regional kitchen',amenity:'restaurant',cuisine:'himachali'}},{type:'node',id:2,lat:0,lon:0,tags:{name:'Far away',tourism:'hotel'}},{type:'node',id:3,tags:{name:'Missing location',tourism:'hotel'}}];const ranked=rankNearby(fixture,plan,t);assert.equal(ranked.length,1);assert.equal(ranked[0].localMatch,true);assert.equal(ranked[0].distanceKm,0);assert.equal(ranked[0].source,'openstreetmap');assert.ok(!('rating' in ranked[0]));});
test('hotel API searches use the requested nearby anchor and bounded radius',()=>{const q=query({latitude:26.925,longitude:75.82,radiusKm:2,areaName:'Near planned stop'});assert.equal(hotelPayload(q).geolocation.latitude,26.925);assert.equal(hotelPayload(q).geolocation.radius,2);assert.throws(()=>query({latitude:0,longitude:0}));assert.throws(()=>query({radiusKm:99}));const buses=demoOffers(query({kind:'bus'}));assert.ok(buses.length>0);assert.ok(buses.every(o=>o.kind==='bus'&&o.price>0));assert.ok(demoOffers(query({kind:'vehicle',adults:20,rooms:1})).every(o=>o.capacity>=20));});
test('condition provider failures stay unavailable and do not create synthetic alerts',async()=>{const t=trip(),plan=buildDemoItinerary(t);const c=await getConditions(t,plan,async()=>{throw new Error('Offline fixture');});assert.equal(c.disasters.status,'unavailable');assert.equal(c.traffic.status,'not-configured');assert.deepEqual(c.alerts,[]);assert.deepEqual(c.legs,[]);assert.equal(c.weather.source,'unavailable');});

const {analytics,expenseSchema,publicSummary,sharedSummarySchema}=require('../lib/journal.ts');
const {offlineHtml,offlineMap}=require('../lib/offline.ts');
const {roadRoute,routeKey}=require('../lib/routing.ts');
const journal=()=>({id:'16a04491-010f-4bfc-b565-f28d3196e749',preferences:trip({budget:1000,travellers:2}),itinerary:buildDemoItinerary(trip({budget:1000,travellers:2})),expenses:[],visited:[],reflection:'Private memory',completed:false,photos:[],updatedAt:'2026-10-15T10:00:00Z'});
const expense=(n,date='2026-10-15')=>({id:require('node:crypto').randomUUID(),category:'Food',amountPaise:n,date,note:'Private restaurant bill',paidBy:'Private name'});
test('budget analytics use integer paise, exact categories, reserve and negative remaining',()=>{const r=journal();r.expenses=[expense(10005),expense(20010,'2026-10-16'),expense(100000)];const a=analytics(r);assert.equal(a.actual,1300.15);assert.equal(a.remaining,-300.15);assert.equal(a.perPerson,650.075);assert.equal(a.categories.find(c=>c.name==='Food').actual,1300.15);assert.equal(a.daily.at(-1).cumulative,1300.15);assert.equal(analytics(journal()).actual,0);assert.throws(()=>expenseSchema.parse(expense(1.5)));assert.throws(()=>expenseSchema.parse(expense(-1)));assert.throws(()=>expenseSchema.parse(expense(1,'2026-02-30')));});
test('public recap is an explicit whitelist; spending is opt-in',()=>{const r=journal();r.expenses=[expense(10005)];r.photos=[{path:'private-user/image.jpg',name:'Private photo'}];r.visited=r.itinerary.days.flatMap(d=>d.activities).filter(a=>a.placeId).map(a=>a.placeId);const s=publicSummary(r),raw=JSON.stringify(s);assert.ok(s.placesVisited>0);assert.ok(!('recordedSpend' in s));for(const secret of ['Private memory','Private name','Private restaurant bill','private-user',r.itinerary.startDate])assert.ok(!raw.includes(secret));assert.equal(publicSummary(r,true).recordedSpend,100.05);assert.equal(sharedSummarySchema.safeParse(s).success,true);assert.equal(sharedSummarySchema.safeParse({...s,highlights:[{}]}).success,false);});
test('offline pack escapes venue/user content and contains contacts and standalone map',()=>{const r=journal();r.itinerary.tripSummary='<script>alert("x")</script>';r.itinerary.days[0].activities[0].name='<img src=x onerror=alert(1)>';const html=offlineHtml(r.itinerary);assert.ok(html.includes('&lt;script&gt;'));assert.ok(!html.includes('<script>'));assert.ok(!html.includes('<img src=x'));assert.match(html,/112/);assert.match(html,/1363/);assert.match(html,/<svg/);assert.ok(!/\b(?:src|href)="https?:/.test(html));assert.match(offlineMap(r.itinerary),/stop order only/);});
test('OSRM geometry, travel time and leg units are checked with mocked HTTP',async()=>{const points=[{latitude:26.9,longitude:75.8},{latitude:26.91,longitude:75.81}];let called;const result=await roadRoute(points,async u=>{called=u;return new Response(JSON.stringify({code:'Ok',routes:[{distance:2500,duration:601,geometry:{coordinates:[[75.8,26.9],[75.81,26.91]]},legs:[{distance:2500,duration:601}]}]}));});assert.equal(result.distanceKm,2.5);assert.equal(result.durationMinutes,11);assert.equal(result.legs[0].minutes,11);assert.ok(called.includes(routeKey(points)));await assert.rejects(()=>roadRoute([{latitude:200,longitude:0},points[1]]));await assert.rejects(()=>roadRoute(points,async()=>new Response('{"code":"NoRoute"}')));});
test('cloud sync acknowledgement does not erase edits made while saving',()=>{const memory=new Map();global.localStorage={getItem:k=>memory.get(k)||null,setItem:(k,v)=>memory.set(k,v)};const {useTravelStore}=require('../lib/travel-store.ts');const r=journal();useTravelStore.setState({records:[r],hydrated:true});useTravelStore.getState().change(r.id,{reflection:'New edit'});const newer=useTravelStore.getState().records[0].updatedAt;useTravelStore.getState().markSynced(r.id,'owner',r.updatedAt,1);assert.equal(useTravelStore.getState().records[0].pendingSync,true);assert.equal(useTravelStore.getState().records[0].reflection,'New edit');useTravelStore.getState().markSynced(r.id,'owner',newer,2);assert.equal(useTravelStore.getState().records[0].pendingSync,false);assert.equal(useTravelStore.getState().records[0].cloudVersion,2);delete global.localStorage;});

const {acceptGeneratedPlan,itineraryPrompt,completedDays,modelResponseSchema}=require('../lib/ai-itinerary.ts');
const {readPlanStream}=require('../lib/plan-stream.ts');
function generatedFixture(){return {tripSummary:'A personalised short visit',days:[{day:1,date:'2026-10-15',title:'One thoughtful day',summary:'A meal and a riverside visit before departure.',lodgingCost:0,walkingKm:1,activities:[{time:'10:00',endTime:'11:00',name:'A new Gemini-selected riverside stop',type:'activity',location:'Manali',description:'Explore the riverfront at a comfortable pace. Take time for the views and neighbourhood life.',whyVisit:'A relaxed nature stop.',insiderTip:'Check riverside access with locals.',alternative:'Rest at your accommodation.',bookingNote:'Confirm access on the day.',accessibilityNote:'Surface conditions are unverified.',estimatedCost:200,indoor:false,localExperience:true,latitude:32.24,longitude:77.19,distanceKm:null},{time:'17:15',endTime:'18:00',name:'Departure buffer',type:'transport',location:'Manali',description:'Leave time for the departure connection.',whyVisit:'Protect departure time.',insiderTip:'Confirm your pickup location.',alternative:'Ask your transport operator.',bookingNote:'Confirm your ticket.',accessibilityNote:'Ask about boarding assistance.',estimatedCost:300,indoor:false,localExperience:false,latitude:null,longitude:null,distanceKm:null}]}],intercityAllowance:500,packingSuggestions:['Comfortable shoes'],travelTips:['Check local conditions'],assumptions:['Costs are group estimates.']};}
const aiTrip=()=>trip({destination:'Manali',endDate:'2026-10-15',arrivalTime:'10:00',departureTime:'18:00'});
test('Gemini owns generated content: new non-catalog places survive validation and totals are recomputed',()=>{const p=acceptGeneratedPlan(generatedFixture(),aiTrip(),'fixture-model');assert.equal(p.days[0].activities[0].name,'A new Gemini-selected riverside stop');assert.equal(p.generation.provider,'gemini');assert.equal(p.generation.model,'fixture-model');assert.ok(p.days[0].activities[0].placeId.startsWith('ai-'));assert.match(p.days[0].activities[0].locationAccuracy,/Gemini/);assert.equal(p.estimatedCost,1000+Math.round(aiTrip().budget*(aiTrip().reservePercent??10)/100));assert.ok(!itineraryPrompt(aiTrip()).includes('FIXED SCHEDULE'));assert.ok(modelResponseSchema().properties.days);});
test('AI schedule validation rejects wrong dates, overlap, excess walking and unprotected departure',()=>{for(const mutate of [r=>r.days[0].date='2026-10-16',r=>r.days[0].activities[1].time='10:30',r=>r.days[0].walkingKm=25,r=>r.days[0].activities[1].endTime='19:00',r=>r.days[0].activities[1].name='Leave later']){const r=generatedFixture();mutate(r);assert.throws(()=>acceptGeneratedPlan(r,aiTrip(),'fixture'));}});
test('AI unmapped sights stay reviewable and far-away coordinates are not mapped',()=>{const r=generatedFixture();r.days[0].activities[0].latitude=0;r.days[0].activities[0].longitude=0;const a=acceptGeneratedPlan(r,aiTrip(),'fixture').days[0].activities[0];assert.equal(a.latitude,undefined);assert.ok(a.placeId);r.days[0].activities[0].latitude=null;r.days[0].activities[0].longitude=null;assert.ok(acceptGeneratedPlan(r,aiTrip(),'fixture').days[0].activities[0].placeId);});
test('incremental JSON day parser handles strings, nested objects and chunk boundaries',()=>{const r=generatedFixture();r.days[0].summary='A quote: " and brackets } [ stay inside text';const text=JSON.stringify(r);assert.equal(completedDays(text.slice(0,text.indexOf('intercityAllowance')-2)).length,1);assert.equal(completedDays(text.slice(0,100)).length,0);assert.deepEqual(completedDays(text),r.days);});
test('SSE reader reconstructs split frames and does not publish a cut-off plan',async()=>{const bytes=new TextEncoder().encode('event: status\ndata: {"message":"Writing…"}\n\nevent: complete\ndata: {"itinerary":{"days":[]}}\n\n');const response=new Response(new ReadableStream({start(c){for(let i=0;i<bytes.length;i+=3)c.enqueue(bytes.slice(i,i+3));c.close();}}));const events=[];await readPlanStream(response,(e,d)=>events.push([e,d]));assert.equal(events[0][1].message,'Writing…');assert.equal(events[1][0],'complete');await assert.rejects(()=>readPlanStream(new Response('event: status\ndata: {"message":"Waiting"}\n\n'),()=>{}),/before the itinerary/);await assert.rejects(()=>readPlanStream(new Response('event: error\ndata: {"error":"Quota reached"}\n\n'),()=>{}),/Quota reached/);});
test('missing Gemini key returns a setup error with no sample itinerary',async()=>{const saved=process.env.GEMINI_API_KEY;delete process.env.GEMINI_API_KEY;try{const endpoint=require('../app/api/gemini/route.ts');const r=await endpoint.POST(new Request('http://localhost/api/gemini',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({trip:aiTrip()})}));const data=await r.json();assert.equal(r.status,503);assert.equal(data.code,'GEMINI_NOT_CONFIGURED');assert.equal(data.itinerary,undefined);}finally{if(saved)process.env.GEMINI_API_KEY=saved;}});
test('Gemini diagnostics identify model and key setup errors',()=>{const endpoint=require('../app/api/gemini/route.ts');const modelError=new Error('models/gemini-3.6-flash is not found for API version');modelError.status=404;assert.match(endpoint.geminiErrorText(modelError,'gemini-3.6-flash'),/not available.*GEMINI_MODEL/);assert.equal(endpoint.isModelAccessError(modelError),true);const keyError=new Error('API key not valid. Please pass a valid API key.');keyError.status=400;assert.match(endpoint.geminiErrorText(keyError,'gemini-2.5-flash'),/rejected the API key/);const quotaError=new Error('Resource exhausted, quota exceeded');quotaError.status=429;assert.match(endpoint.geminiErrorText(quotaError,'gemini-2.5-flash'),/quota/);});
test('replanning never creates a fresh sample itinerary when none was supplied',async()=>{const endpoint=require('../app/api/replan/route.ts');const r=await endpoint.POST(new Request('http://localhost/api/replan',{method:'POST',body:JSON.stringify({trip:aiTrip()})}));assert.equal(r.status,400);assert.match((await r.json()).error,/Gemini first/);});

const {BudgetExceededError,assertPlanBudget,affordableReplacement}=require('../lib/budget-policy.ts');
const {appendTrackPoint,trackDistance,trackSegments,directionsUrl}=require('../lib/tracking.ts');
const {daySlots,demoRecommendations,nearbyForSlot}=require('../lib/recommendations.ts');
test('Gemini over-budget output is rejected, including reserve, without falsifying cost lines',()=>{const raw=generatedFixture(),t={...aiTrip(),budget:1000,reservePercent:10};assert.throws(()=>acceptGeneratedPlan(raw,t,'fixture'),e=>e instanceof BudgetExceededError&&e.suggestedBudget===1200);assert.equal(raw.days[0].activities[0].estimatedCost,200);const ok={...t,budget:1200};assert.ok(acceptGeneratedPlan(raw,ok,'fixture').estimatedCost<=ok.budget);});
test('budget policy uses actual line items and preserves the reserve on suggested increase',()=>{const p=acceptGeneratedPlan(generatedFixture(),aiTrip(),'fixture');p.estimatedCost=1;p.days[0].activities[0].estimatedCost=50000;assert.throws(()=>assertPlanBudget(p,aiTrip()),e=>e instanceof BudgetExceededError&&e.suggestedBudget>50000);});
test('recommendation prices scale with rooms/group and never exceed a block or total budget',()=>{const p=buildDemoItinerary(trip({budget:100000,roomCount:2}));for(const day of p.days)for(const slot of daySlots(p,day))for(const d of demoRecommendations(p,slot,trip({roomCount:2}))){assert.ok(d.groupPrice<=slot.allowance);assert.ok(p.estimatedCost-slot.allowance+d.groupPrice<=p.budgetLimit);if(d.unit==='room')assert.equal(d.groupPrice,d.rate*2);if(d.unit==='person')assert.equal(d.groupPrice,d.rate*p.travellers);}assert.equal(affordableReplacement(p,100,101),false);assert.equal(affordableReplacement({...p,budgetLimit:1},100,0),false);assert.equal(daySlots(p,p.days.at(-1)).some(s=>s.kind==='hotel'),false);});
test('flight examples require enough group budget and obey explicit transport preference',()=>{const p=buildDemoItinerary(trip({budget:100000})),slot={id:'i',kind:'intercity',name:'Return journey',allowance:42000,area:'Delhi'};assert.equal(demoRecommendations(p,slot,trip({transport:'Any'}))[0].id,'travel-flight');assert.ok(!demoRecommendations(p,{...slot,allowance:5000},trip({transport:'Any'})).some(d=>d.id==='travel-flight'));assert.ok(demoRecommendations(p,slot,trip({transport:'Bus'})).every(d=>d.id==='travel-bus'));});
test('real venue recommendations filter day and radius without making up prices',()=>{const p=acceptGeneratedPlan(generatedFixture(),aiTrip(),'fixture');p.nearby={places:[{id:'near',kind:'restaurant',latitude:32.241,longitude:77.19,distanceKm:.1,dayNumbers:[1],localMatch:true},{id:'far',kind:'restaurant',latitude:28,longitude:77,distanceKm:1,dayNumbers:[1]},{id:'other-day',kind:'restaurant',latitude:32.24,longitude:77.19,distanceKm:.1,dayNumbers:[2]}]};const result=nearbyForSlot(p,1,{kind:'restaurant',latitude:32.24,longitude:77.19},3);assert.deepEqual(result.map(p=>p.id),['near']);assert.equal(result[0].price,undefined);});
const gps=(extra={})=>({latitude:32.24,longitude:77.19,timestamp:1000000,accuracy:10,segment:1,...extra});
test('GPS recording ignores poor fixes, jitter and impossible jumps; resumes have no imaginary connecting distance',()=>{const first=gps();let points=appendTrackPoint([],first);assert.equal(appendTrackPoint(points,gps({timestamp:1001000,accuracy:300})),points);assert.equal(appendTrackPoint(points,gps({timestamp:1001000,latitude:0})),points);assert.equal(appendTrackPoint(points,gps({timestamp:1001000,latitude:32.240001})),points);points=appendTrackPoint(points,gps({timestamp:1010000,latitude:32.241}));const km=trackDistance(points);assert.ok(km>.1&&km<.12);points=appendTrackPoint(points,gps({timestamp:1015000,latitude:28,segment:2}));assert.equal(trackDistance(points),km);assert.equal(trackSegments(points).length,2);points=appendTrackPoint(points,gps({timestamp:1400000,latitude:27,segment:2}));assert.equal(trackDistance(points),km);assert.equal(trackSegments(points).length,3);});
test('directions open the in-app map with actual destination and live origin coordinates',()=>{const u=new URL(directionsUrl({latitude:28.61,longitude:77.21},{latitude:28.62,longitude:77.22}),'http://localhost');assert.equal(u.pathname,'/trip-map');assert.equal(u.searchParams.get('originLat'),'28.62');assert.equal(u.searchParams.get('originLng'),'77.22');assert.equal(u.searchParams.get('lat'),'28.61');assert.equal(u.searchParams.get('lng'),'77.21');assert.equal(new URL(directionsUrl({latitude:1,longitude:2}),'http://localhost').searchParams.has('originLat'),false);});
test('SSE carries budget action metadata through to the planner',async()=>{const {PlanStreamError}=require('../lib/plan-stream.ts');await assert.rejects(()=>readPlanStream(new Response('event: error\ndata: {"error":"Needs more budget","code":"BUDGET_EXCEEDED","suggestedBudget":1200}\n\n'),()=>{}),e=>e instanceof PlanStreamError&&e.suggestedBudget===1200);});
test('nearby emergency API validates GPS, uses its centre, and keeps precise searches uncached',async()=>{const endpoint=require('../app/api/places/route.ts');for(const query of ['lat=&lng=77','lat=91&lng=77','lat=28&lng=181','lat=28','lat=NaN&lng=77','lat=28&lng=77&radius=100'])assert.equal((await endpoint.GET(new Request('http://localhost/api/places?'+query))).status,400);const original=global.fetch;let calls=0;global.fetch=async(url,options)=>{calls++;assert.match(String(options.body),/28.6%2C77.2/);assert.ok(!String(options.body).includes('restaurant'));return Response.json({elements:[{type:'node',id:1,lat:28.601,lon:77.2,tags:{amenity:'hospital',name:'Test hospital'}},{type:'node',id:2,lat:20,lon:77,tags:{amenity:'police',name:'Far police'}}]});};try{for(let i=0;i<2;i++){const r=await endpoint.GET(new Request('http://localhost/api/places?lat=28.6&lng=77.2&services=emergency'));assert.equal(r.status,200);assert.equal(r.headers.get('cache-control'),'private, no-store');assert.equal((await r.json()).points.length,1);}assert.equal(calls,2);}finally{global.fetch=original;}});

const {offerBudgetState,assertBookingBudget}=require('../lib/booking/budget.ts');
const {parseSky,parseAirQuality,compassDirection}=require('../lib/weather-dashboard.ts');
test('vehicle allowance exposes upgrades but locks costs above INR 1000 for the entire hire',()=>{
 const q=query({kind:'vehicle',adults:2,rooms:1,checkOut:'2026-10-15',budgetLimit:1000});const cars=demoOffers(q),economy=cars.find(o=>/hatchback/i.test(o.name));assert.ok(economy);assert.equal(economy.price,940);assert.equal(offerBudgetState(economy,1000).available,true);assert.doesNotThrow(()=>assertBookingBudget(economy));const upgrade=cars.find(o=>o.price>1000);assert.ok(upgrade);assert.equal(offerBudgetState(upgrade,1000).shortfall,upgrade.price-1000);assert.throws(()=>assertBookingBudget(upgrade),/Increase the budget/);
 const longer=demoOffers({...q,checkOut:'2026-10-18'}).find(o=>o.id===economy.id);assert.ok(longer.price>1000);assert.throws(()=>assertBookingBudget(longer));assert.equal(offerBudgetState({...economy,currency:'EUR'},1000).available,false);for(const budgetLimit of [0,-1,'invalid',Infinity])assert.throws(()=>query({budgetLimit}));
});
test('booking API rejects over-budget search and confirmation tokens',async()=>{
 const endpoint=require('../app/api/bookings/route.ts'),q=query({kind:'vehicle',adults:2,rooms:1,checkOut:'2026-10-15',budgetLimit:1000}),offer=demoOffers(q).find(o=>o.price>1000);
 for(const action of ['quote','confirm']){const token=signOffer(offer,action==='quote'?'search':'quote');const r=await endpoint.POST(new Request('http://localhost/api/bookings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,token,acceptTerms:true})}));assert.equal(r.status,400);assert.match((await r.json()).error,/Increase the budget/);}
});
test('weather dashboard retains missing measurements and aligns hourly data to IST',()=>{
 const raw={current:{time:'2026-09-11T10:00',temperature_2m:22,precipitation:null},hourly:{time:['2026-09-10T10:00','2026-09-11T10:00','2026-09-11T11:00','2026-09-13T10:00'],temperature_2m:[20,22,null,24],precipitation_probability:[0,null,20,30]}};const parsed=parseSky(raw,new Date('2026-09-11T04:30:00Z'));assert.equal(parsed.hourly.length,1);assert.equal(parsed.hourly[0].time,'2026-09-11T10:00');assert.equal(parsed.hourly[0].rainProbability,null);assert.equal(parsed.skyCurrent.precipitation,null);assert.equal(compassDirection(90),'E');assert.equal(compassDirection(null),'—');
 assert.equal(parseAirQuality({current:{time:'x',us_aqi:null}}),undefined);assert.equal(parseAirQuality({current:{time:'x',us_aqi:120,pm2_5:null}}).label,'Unhealthy for sensitive groups');assert.equal(parseAirQuality({current:{time:'x',us_aqi:25,pm2_5:null}}).pm25,null);
});
