'use client';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {MapPin,Clock3,ArrowRight,ChevronDown,Utensils,Camera,Car,Hotel,Sparkles,Download,ShieldCheck,RefreshCw} from 'lucide-react';
import type {Itinerary,ItineraryActivity} from '@/lib/itinerary';
import {formatINR} from '@/lib/trip';
import ConditionsPanel from '@/app/components/ConditionsPanel';
import BudgetRecommendations from '@/app/components/BudgetRecommendations';
import {defaultTrip,TRIP_STORAGE_KEY} from '@/lib/trip';
import {useTravelStore} from '@/lib/travel-store';
import {recordKey} from '@/lib/journal';
import NearbyPanel from '@/app/components/NearbyPanel';
import TripDownloads from '@/app/components/TripDownloads';
import PlaceRating from '@/app/components/PlaceRating';
import {rememberItinerary} from '@/lib/travel-store';
const tabs=['Day plan','Food & stays','Conditions','Budget','Downloads'];
export default function ItineraryPage(){const [plan,setPlan]=useState<Itinerary|null>(null),[loaded,setLoaded]=useState(false),[day,setDay]=useState(1),[tab,setTab]=useState('Day plan'),[budgetInput,setBudgetInput]=useState(''),[budgetMessage,setBudgetMessage]=useState('');useEffect(()=>{try{const value=JSON.parse(localStorage.getItem('travelsetu_itinerary')||'null');if(value?.days?.length){setPlan(value);setBudgetInput(String(value.budgetLimit||value.estimatedCost));};}catch{}setLoaded(true);},[]);if(!plan)return <main className="page-shell"><div className="container-page"><h1 className="page-title">Your itinerary</h1><div className="panel mt-6 max-w-2xl"><Sparkles className="text-[#075b3d]"/><h2 className="mt-4 text-xl font-semibold">{loaded?'Let’s plan something good.':'Opening your trip…'}</h2><p className="mt-3 text-sm muted">Tell us where, when and how you like to travel.</p><Link href="/plan-trip" className="btn-primary mt-5">Create with Gemini<ArrowRight size={16}/></Link></div></div></main>;
 const selected=plan.days.find(d=>d.day===day)||plan.days[0],weather=plan.conditions?.weather.daily.find(w=>w.date===selected.date),budget=plan.budgetBreakdown;function update(p:Itinerary){setPlan(p);rememberItinerary(p);}
 function reviewBudget(){const next=Number(budgetInput);if(!Number.isFinite(next)||next<1000||next>10000000){setBudgetMessage('Enter a group budget from ₹1,000 to ₹1,00,00,000.');return;}try{useTravelStore.getState().hydrate();const saved=useTravelStore.getState().records.find(r=>recordKey(r.itinerary)===recordKey(plan!));const prior=JSON.parse(localStorage.getItem('travelsetu_trip')||'null');const matches=prior?.destination===plan!.destination&&prior?.startDate===plan!.startDate;const draft={...defaultTrip(),...(saved?.preferences||(matches?prior:{})),from:plan!.from,destination:plan!.destination,startDate:plan!.startDate,endDate:plan!.endDate,travellers:plan!.travellers,budget:next};localStorage.setItem(TRIP_STORAGE_KEY,JSON.stringify(draft));window.location.href='/plan-trip?budget='+next;}catch{setBudgetMessage('The revised budget could not be saved. Open Plan trip to edit it.');}}

 return <main className="page-shell"><div className="container-page"><div className="page-head"><div><p className="eyebrow">{(plan as Itinerary&{generation?:{provider:string}}).generation?.provider==='gemini'?'Created with Gemini':'Saved itinerary'}</p><h1 className="page-title">{plan.destination}, your way.</h1><p className="text-sm muted">{plan.startDate} — {plan.endDate} · {plan.travellers} travellers</p></div><div className="page-actions"><Link href="/trip-map" className="btn-secondary"><MapPin size={16}/>View map</Link><Link href="/replanning" className="btn-secondary"><RefreshCw size={16}/>Dynamic replan</Link><button className="btn-primary" onClick={()=>setTab('Downloads')}><Download size={16}/>Save offline</button></div></div><details className="quiet-details mt-5" open={plan.budgetLimit!==undefined&&plan.estimatedCost>plan.budgetLimit?true:undefined}><summary>Review budget · {formatINR(plan.budgetLimit||plan.estimatedCost)} group limit</summary><p className="text-sm muted">Update the draft here, then generate a fresh plan with Gemini. Your saved itinerary remains available.</p><div className="mt-3 flex flex-wrap items-end gap-3"><label className="text-sm">Group budget · ₹<input className="input mt-1" type="number" min={1000} max={10000000} value={budgetInput} onChange={e=>setBudgetInput(e.target.value)}/></label><button className="btn-primary" onClick={reviewBudget}>Review & replan</button></div>{budgetMessage&&<p role="alert" className="mt-2 text-sm">{budgetMessage}</p>}</details><div className="workspace-tabs" role="tablist" aria-label="Itinerary sections">{tabs.map(t=><button role="tab" id={'tab-'+t} aria-controls="itinerary-content" aria-selected={tab===t} key={t} onClick={()=>setTab(t)}>{t}</button>)}</div><div id="itinerary-content" role="tabpanel" aria-labelledby={'tab-'+tab}>
 {tab==='Day plan'&&<div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1fr)_260px]"><section className="min-w-0"><div className="mb-5 flex gap-2 overflow-auto pb-2" aria-label="Choose itinerary day">{plan.days.map(d=><button className={'day-picker '+(day===d.day?'active':'')} aria-pressed={day===d.day} key={d.day} onClick={()=>setDay(d.day)}><strong>Day {d.day}</strong><span>{new Date(d.date+'T00:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</span></button>)}</div><div className="mb-6 flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{selected.title}</h2><p className="mt-1 text-sm muted">{selected.activities.length} planned blocks · {formatINR(selected.estimatedCost)} estimate</p></div><details className="max-w-lg text-sm muted"><summary>Day overview</summary><p className="mt-3 leading-7">{selected.summary}</p></details></div><div className="itinerary-timeline">{selected.activities.map(a=><Activity key={a.id} item={a} destination={plan.destination}/>)}</div><BudgetRecommendations plan={plan} day={selected.day}/></section><aside className="space-y-5 xl:sticky xl:top-24"><section className="panel"><h2 className="font-semibold">Trip at a glance</h2><div className="mt-5 grid grid-cols-2 gap-y-5"><div className="trip-stat">Duration<strong>{plan.duration} days</strong></div><div className="trip-stat">Trip estimate<strong>{formatINR(plan.estimatedCost)}</strong></div></div><details className="mt-5 border-t pt-4 text-sm"><summary>About this journey</summary><p className="mt-3 detail-copy">{plan.tripSummary}</p></details></section><section className="panel"><div className="flex items-center gap-2 font-semibold"><ShieldCheck size={19}/>Before you leave</div><p className="mt-3 text-sm muted">{weather?`${weather.description} · ${weather.minTemperature}–${weather.maxTemperature}°C`:'Forecast not available for this day.'}</p>{weather?.risk==='AT RISK'&&<p className="mt-3 text-sm text-amber-800">Outdoor plans need review.</p>}<button className="mt-4 text-sm font-semibold text-[#075b3d]" onClick={()=>setTab('Conditions')}>Check conditions & changes →</button></section><Link href="/post-trip" className="panel block"><h2 className="font-semibold">Make it a memory</h2><p className="mt-2 text-sm muted">Mark visits, review places and share.</p><span className="mt-4 block text-sm font-semibold text-[#075b3d]">Open travel journal →</span></Link></aside></div>}
 {tab==='Food & stays'&&<><BudgetRecommendations plan={plan} day={day}/><NearbyPanel itinerary={plan} day={day} onUpdate={nearby=>update({...plan,nearby})}/></>}
 <div hidden={tab!=='Conditions'}><ConditionsPanel itinerary={plan} onUpdate={update}/></div>
 {tab==='Budget'&&<section className="panel max-w-4xl"><div className="page-head"><div><h2 className="text-xl font-semibold">Your planning estimate</h2><p className="mt-2 text-sm muted">For the whole group. Prices need confirmation.</p></div><Link href="/budget" className="btn-primary">Track spending</Link></div><div className="mt-6 grid gap-4 sm:grid-cols-3">{budget&&Object.entries({Accommodation:budget.stay,Food:budget.food,Activities:budget.activities,'Local travel':budget.localTransport,'Intercity allowance':budget.intercityTransport,Reserve:budget.reserve}).map(([label,value])=><div className="rounded-xl bg-[#f2f5ee] p-4" key={label}><p className="text-sm muted">{label}</p><strong className="mt-2 block text-xl">{formatINR(value)}</strong></div>)}</div><p className="mt-6 font-semibold">Total {formatINR(plan.estimatedCost)}{plan.budgetLimit&&plan.estimatedCost>plan.budgetLimit?` · ${formatINR(plan.estimatedCost-plan.budgetLimit)} over your budget`:''}</p><details className="quiet-details mt-6"><summary>Assumptions & things to confirm</summary><ul className="list-disc space-y-3 pl-5 detail-copy">{[...(plan.warnings||[]),...(plan.assumptions||[])].map((w,i)=><li key={i}>{w}</li>)}</ul></details></section>}
 {tab==='Downloads'&&<><TripDownloads plan={plan}/><details className="quiet-details mt-5"><summary>Packing list & travel tips</summary><div className="grid gap-5 sm:grid-cols-2">{[plan.packingSuggestions,plan.travelTips].map((list,n)=><ul className="list-disc space-y-3 pl-5 detail-copy" key={n}>{list.map((s,i)=><li key={i}>{s}</li>)}</ul>)}</div></details></>}
 </div></div></main>;
}
function Activity({item:a,destination}:{item:ItineraryActivity;destination:string}){const Icon=a.type==='food'?Utensils:a.type==='transport'?Car:a.type==='stay'?Hotel:Camera;return <div className="timeline-row"><div className="timeline-time">{a.time}<small>{a.endTime}</small></div><div className="timeline-dot"><Icon size={16}/></div><details className="activity-card"><summary><div className="min-w-0"><span className="activity-type">{a.type.replace('-',' ')}{a.localExperience?' · Local':''}</span><h3>{a.name}</h3><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs muted"><span className="flex items-center gap-1"><MapPin size={13}/>{a.location}</span><span className="flex items-center gap-1"><Clock3 size={13}/>{a.durationMinutes} min</span><span>{formatINR(a.estimatedCost)} estimate</span></div></div><ChevronDown size={18} className="activity-chevron"/></summary>{a.adaptationReason&&<p className="notice mt-4">{a.adaptationReason}</p>}<div className="activity-detail"><p>{a.description}</p>{a.whyVisit&&<p><strong>What to experience</strong>{a.whyVisit}</p>}{a.insiderTip&&<p><strong>Local tip</strong>{a.insiderTip}</p>}{a.bookingNote&&<p><strong>Before you go</strong>{a.bookingNote}</p>}{a.accessibilityNote&&<p><strong>Access & comfort</strong>{a.accessibilityNote}</p>}{a.alternative&&<p><strong>If plans change</strong>{a.alternative}</p>}{['activity','food','stay','transport'].includes(a.type)&&<><Link href={`/trip-map?lat=${a.latitude??''}&lng=${a.longitude??''}&name=${encodeURIComponent(a.name)}`} className="font-semibold text-[#075b3d]">Open navigation in TravelSetu →</Link><PlaceRating id={a.placeId||`visit:${destination.toLowerCase()}:${a.name.toLowerCase().trim()}`} name={a.name} kind={a.type==='food'?'restaurant':a.type==='stay'?'hotel':a.type==='transport'?'transport':'attraction'} latitude={a.latitude} longitude={a.longitude}/></>}</div></details></div>;}
