import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, ArrowRight, MapPin, Utensils, Route, CalendarDays } from "lucide-react";
import destinations from "@/data/destinations.json";
import places from "@/data/places.json";
import { formatINR } from "@/lib/trip";
export function generateStaticParams(){return destinations.map(d=>({id:d.id}));}
export async function generateMetadata({params}:{params:Promise<{id:string}>}){const {id}=await params;const d=destinations.find(d=>d.id===id);return {title:d?`${d.name} travel guide | TravelSetu`:'Destination | TravelSetu'};}
export default async function DestinationPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const d=destinations.find(x=>x.id===id);if(!d)notFound();return <main className="page-shell"><div className="container-page"><Link href="/explore" className="inline-flex items-center gap-2 text-sm font-bold text-[#075b3d]"><ArrowLeft size={16}/> Back to Explore</Link><div className="mt-7 grid gap-8 lg:grid-cols-[1.2fr_.8fr]"><div><p className="eyebrow">{d.region} India · {d.state}</p><h1 className="page-title">A little more {d.name}.</h1><p className="text-xl leading-8 muted">{d.description}</p><div className="mt-6 flex flex-wrap gap-2">{d.category.map(c=><span className="chip" key={c}>{c}</span>)}</div><Link className="btn-primary mt-8" href={`/plan-trip?destination=${encodeURIComponent(d.name)}`}>Plan my {d.name} trip <ArrowRight size={17}/></Link></div><div className="panel"><h2 className="text-xl font-bold">Before you go</h2><dl className="mt-4 space-y-4"><div><dt className="flex gap-2 text-sm muted"><CalendarDays size={17}/> A good first visit</dt><dd className="mt-1 font-bold">{d.idealDays} days · seasonal guide: {d.bestTime}</dd></div><div><dt className="text-sm muted">Estimated local budget, per person per day</dt><dd className="font-bold">From {formatINR(d.dailyBudget)}</dd></div><div><dt className="flex gap-2 text-sm muted"><Route size={17}/> Getting there</dt><dd className="mt-1 text-sm leading-6">{d.gettingThere}</dd></div><div><dt className="flex gap-2 text-sm muted"><Utensils size={17}/> Flavours to explore</dt><dd className="mt-1 text-sm">{d.localFood.join(' · ')}</dd></div></dl></div></div>
 <section className="mt-12"><h2 className="text-2xl font-bold">Put these on your list</h2><div className="mt-6 grid gap-5 md:grid-cols-2">{places.filter(p=>p.destinationId===id).map((p,i)=><article key={p.id} className="panel"><div className="flex items-start gap-4"><span className="text-3xl font-black text-[#aec9e6]">{String(i+1).padStart(2,'0')}</span><div><h3 className="text-lg font-bold">{p.name}</h3><p className="mt-2 text-sm muted">{p.description}</p><p className="mt-3 text-sm">Allow about {p.durationMinutes} minutes · {p.category}</p><p className="mt-2 text-sm muted">{p.visitTip}</p><Link className="mt-4 inline-flex items-center gap-1 text-sm font-bold text-[#075b3d]" href={`/trip-map?lat=${p.latitude}&lng=${p.longitude}&name=${encodeURIComponent(p.name)}`}><MapPin size={15}/> Open in TravelSetu map</Link></div></div></article>)}</div></section><div className="notice mt-8">This is an editorial starting point. Locations are approximate and costs are estimates. Verify hours, admission, access and local conditions before travelling. <a className="underline" target="_blank" rel="noreferrer" href={d.sourceUrl}>Browse official India tourism information</a>.</div></div></main>}
