"use client";
import Link from 'next/link';
import { useEffect,useState } from 'react';
import { ArrowRight,CalendarDays,Ticket } from 'lucide-react';
import { SAVED_TRIP_STORAGE_KEY,TRIP_STORAGE_KEY,formatINR } from '@/lib/trip';
import type { TripForm } from '@/types/travel';
import type { BookingReceipt } from '@/lib/booking/types';
type Saved=TripForm&{id:string;createdAt:string};
export default function MyTrips(){const [trips,setTrips]=useState<Saved[]>([]),[bookings,setBookings]=useState<BookingReceipt[]>([]),[active,setActive]=useState<TripForm|null>(null),[message,setMessage]=useState('');useEffect(()=>{try{const t=JSON.parse(localStorage.getItem(SAVED_TRIP_STORAGE_KEY)||'[]'),b=JSON.parse(localStorage.getItem('travelsetu_bookings')||'[]');setTrips(Array.isArray(t)?t:[]);setBookings(Array.isArray(b)?b:[]);setActive(JSON.parse(localStorage.getItem('travelsetu_trip')||'null'));}catch{setMessage('Some saved data could not be read. Your source project and supplier records are unaffected.');}},[]);
function openTrip(t:Saved){try{localStorage.setItem(TRIP_STORAGE_KEY,JSON.stringify(t));localStorage.setItem('travelsetu_trip',JSON.stringify(t));window.location.href='/plan-trip';}catch{setMessage('Could not open this saved draft.');}}
return <main className="page-shell"><div className="container-page"><p className="eyebrow">Keep your ideas together</p><h1 className="page-title">Your next chapters.</h1><p className="muted">Drafts and test booking records stay on this browser. Save generated itineraries to your account from the journal to access them across devices.</p>{message&&<p className="notice mt-5">{message}</p>}{active&&<div className="panel mt-8 border-blue-200"><h2 className="text-2xl font-bold">Continue your {active.destination} trip</h2><p className="mt-3 muted">{active.from} → {active.destination} · {active.startDate} to {active.endDate}</p><div className="mt-5 flex flex-wrap gap-3"><Link className="btn-primary" href="/itinerary">Open itinerary <ArrowRight size={16}/></Link><Link className="btn-secondary" href="/trip-map">See the map</Link><Link className="btn-secondary" href="/marketplace">Find stays & transport</Link></div></div>}
<div className="mt-6 flex flex-wrap gap-3"><Link className="btn-primary" href="/post-trip">Trip journals & reviews</Link><Link className="btn-secondary" href="/budget">Budget analytics</Link><Link className="btn-secondary" href="/account">Cloud saved trips</Link></div><section className="mt-10"><h2 className="text-2xl font-bold">Saved trip drafts ({trips.length})</h2><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{trips.map(t=><article className="panel" key={t.id}><CalendarDays className="text-[#075b3d]"/><h3 className="mt-3 text-xl font-bold">{t.destination}</h3><p className="mt-2 text-sm muted">{t.startDate} → {t.endDate}<br/>{t.travellers} travellers · {formatINR(t.budget)}</p><button className="btn-secondary mt-5" onClick={()=>openTrip(t)}>Open draft <ArrowRight size={16}/></button></article>)}</div>{!trips.length&&<div className="panel mt-5"><p>No saved drafts yet. Save your preferences in the trip planner.</p><Link className="btn-primary mt-4" href="/plan-trip">Plan a trip</Link></div>}</section>
<section className="mt-10"><h2 className="text-2xl font-bold">Booking records ({bookings.length})</h2><div className="mt-5 grid gap-5 md:grid-cols-2">{bookings.map(b=><article className="panel" key={b.id}><span className="chip"><Ticket size={16}/>{b.mode==='demo'?'DEMO RECORD':'SUPPLIER TEST'}</span><h3 className="mt-3 text-xl font-bold">{b.name}</h3><p className="mt-2 font-mono text-sm">{b.reference}</p><p className="mt-3 text-sm muted">{b.startDate} → {b.endDate}</p><p className="mt-2 font-bold">Quoted total: {new Intl.NumberFormat('en-IN',{style:'currency',currency:b.currency}).format(b.price)}</p><p className="notice mt-4">{b.message}</p></article>)}</div>{!bookings.length&&<div className="panel mt-5"><p>No booking records yet.</p><Link className="btn-primary mt-4" href="/marketplace">Compare travel options</Link></div>}</section></div></main>}
