'use client';
import {supabase} from './supabase';
import {useTravelStore} from './travel-store';
import type {TripRecord} from './journal';
import {publicSummary} from './journal';
export async function signedIn(){const client=supabase();if(!client)throw new Error('Cloud storage is not configured. Your work is saved locally.');const {data,error}=await client.auth.getUser();if(error||!data.user)throw new Error('Sign in to save permanent records to your account.');return {client,user:data.user};}
const inFlight=new Map<string,Promise<string>>();
export function saveCloudTrip(record:TripRecord):Promise<string>{const pending=inFlight.get(record.id);if(pending)return pending;const task=writeTrip(record).finally(()=>inFlight.delete(record.id));inFlight.set(record.id,task);return task;}
async function writeTrip(record:TripRecord){const {client,user}=await signedIn();if(record.ownerId&&record.ownerId!==user.id)throw new Error('This trip belongs to a different account.');const version=(record.cloudVersion||0)+1;const payload={id:record.id,owner_id:user.id,destination:record.itinerary.destination,document:{...record,ownerId:user.id,pendingSync:false,cloudVersion:version},version,updated_at:record.updatedAt};
 const query=record.cloudVersion?client.from('trips').update(payload).eq('id',record.id).eq('version',record.cloudVersion):client.from('trips').insert(payload);
 const {data,error}=await query.select('id').maybeSingle();if(error||!data)throw new Error('Sync stopped: this trip may have newer changes on another device, or the connection/setup failed. Your device copy is preserved. Export it before replacing or resolving changes.');
 useTravelStore.getState().markSynced(record.id,user.id,record.updatedAt,version);return record.id;
}
export async function loadCloudTrips(){const {client,user}=await signedIn();const {data,error}=await client.from('trips').select('id,document,updated_at,version').order('updated_at',{ascending:false}).limit(60);if(error)throw new Error('Could not load saved trips. Check your Supabase setup.');const records=(data||[]).flatMap(row=>{const d=row.document as TripRecord;if(!d?.itinerary?.days||!Array.isArray(d.expenses)||!Array.isArray(d.visited))return [];return [{...d,id:row.id,ownerId:user.id,updatedAt:row.updated_at,cloudVersion:row.version,pendingSync:false}];});useTravelStore.getState().merge(records);return records;}
export async function createShare(record:TripRecord,includeBudget:boolean){const {client,user}=await signedIn();await saveCloudTrip(record);const summary=publicSummary(record,includeBudget);const {data,error}=await client.from('trip_shares').insert({owner_id:user.id,trip_id:record.id,summary}).select('token').single();if(error)throw new Error('Could not create a share link.');return {token:data.token as string,url:`${location.origin}/share/${data.token}`};}
export async function revokeShare(token:string){const {client}=await signedIn();const {error}=await client.from('trip_shares').delete().eq('token',token);if(error)throw new Error('Could not revoke this link.');}
export async function uploadPhoto(record:TripRecord,file:File){if(record.photos.length>=20)throw new Error("This album has reached 20 photos.");if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw new Error('Choose a JPG, PNG or WebP image under 5 MB.');const {client,user}=await signedIn();await saveCloudTrip(record);const ext=file.type==='image/jpeg'?'jpg':file.type==='image/png'?'png':'webp',path=`${user.id}/${record.id}/${crypto.randomUUID()}.${ext}`;const {error}=await client.storage.from('trip-photos').upload(path,file,{contentType:file.type,upsert:false});if(error)throw new Error('Photo could not be uploaded. Check storage setup.');const latest=useTravelStore.getState().records.find(r=>r.id===record.id)||record;const photos=[...latest.photos,{path,name:file.name.slice(0,120)}];useTravelStore.getState().change(record.id,{photos});const updated=useTravelStore.getState().records.find(r=>r.id===record.id)!;await saveCloudTrip(updated);return path;}
export async function photoUrl(path:string){const {client}=await signedIn();const {data,error}=await client.storage.from('trip-photos').createSignedUrl(path,600);if(error)throw new Error('Photo unavailable');return data.signedUrl;}
