import type {Itinerary} from './itinerary';
import emergency from '../data/emergency.json';
import {routeKey,type RoadRoute} from './routing';
export function escapeHtml(v:unknown){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));}
export function offlineMap(plan:Itinerary,roads:Record<string,RoadRoute>={}){
 const points=plan.days.flatMap(d=>d.activities.filter(a=>a.type==='activity'&&Number.isFinite(a.latitude)&&Number.isFinite(a.longitude)).map(a=>({name:a.name,latitude:a.latitude!,longitude:a.longitude!,day:d.day})));
 if(!points.length)return '<p>No saved coordinates for this plan.</p>';
 const lines=plan.days.map(day=>{const stops=points.filter(p=>p.day===day.day);const road=stops.length>1?roads[routeKey(stops)]:undefined;return {points:road?.coordinates||stops.map(p=>[p.longitude,p.latitude]),road:!!road};});const all=[...points.map(p=>[p.longitude,p.latitude]),...lines.flatMap(l=>l.points)];
 const minX=Math.min(...all.map(p=>p[0])),maxX=Math.max(...all.map(p=>p[0])),minY=Math.min(...all.map(p=>p[1])),maxY=Math.max(...all.map(p=>p[1]));const x=(v:number)=>50+(v-minX)/Math.max(.005,maxX-minX)*700,y=(v:number)=>450-(v-minY)/Math.max(.005,maxY-minY)*400;
 return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 520" role="img" aria-label="Offline map of saved itinerary stops"><rect width="800" height="520" rx="20" fill="#edf4fa"/><text x="25" y="30" font-family="sans-serif" font-size="15" fill="#234">N ↑ · Saved location overview</text>${lines.map(l=>`<polyline points="${l.points.map(p=>`${x(p[0]).toFixed(1)},${y(p[1]).toFixed(1)}`).join(' ')}" fill="none" stroke="#1670c8" stroke-width="3" ${l.road?'':'stroke-dasharray="7 7"'}/>`).join('')}${points.map((p,i)=>`<circle cx="${x(p.longitude)}" cy="${y(p.latitude)}" r="15" fill="#10243e"/><text x="${x(p.longitude)}" y="${y(p.latitude)+5}" text-anchor="middle" fill="white" font-family="sans-serif" font-size="12">${i+1}</text>`).join('')}<text x="25" y="500" font-family="sans-serif" font-size="12" fill="#53657a">Solid: saved OSRM driving route · Dashed: stop order only · Not navigation</text></svg><ol>${points.map(p=>`<li>Day ${p.day}: ${escapeHtml(p.name)} · ${p.latitude.toFixed(4)}, ${p.longitude.toFixed(4)}</li>`).join('')}</ol>`;
}
export function offlineHtml(plan:Itinerary,roads:Record<string,RoadRoute>={}){const esc=escapeHtml;return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(plan.destination)} offline trip</title><style>body{font:16px/1.6 system-ui,sans-serif;color:#10243e;max-width:960px;margin:auto;padding:24px;background:#f5f8fc}section,header{padding:24px;margin:20px 0;border:1px solid #dce4ec;border-radius:18px;background:white}h1{font-size:36px}h2{margin-top:0}article{border-top:1px solid #e5eaf0;padding:15px 0}small{color:#52657b}svg{width:100%;height:auto}.notice{background:#fff4cc;padding:16px;border-radius:12px}a{color:#065fbd}@media print{body{background:white}section{break-inside:avoid}}</style><header><small>TRAVELSETU · OFFLINE TRIP PACK</small><h1>${esc(plan.destination)}</h1><p>${esc(plan.startDate)} → ${esc(plan.endDate)} · ${plan.travellers} travellers</p><p>${esc(plan.tripSummary)}</p><p class="notice">Saved ${esc(new Date().toISOString())}. This is a snapshot. Weather, road status, alerts and availability can change. A saved plan is not a safety clearance. Follow local official guidance.</p></header><section><h2>Emergency contacts</h2>${emergency.map(c=>`<p><strong>${esc(c.name)}: <a href="tel:${esc(c.number)}">${esc(c.number)}</a></strong><br><small>${esc(c.description)}</small></p>`).join('')}<p>Calls still need a working telephone connection. Official disaster portal: https://sachet.ndma.gov.in/ (internet required).</p></section><section><h2>Saved map & stops</h2>${offlineMap(plan,roads)}<p><small>Saved model estimates, approximate catalog coordinates and community map data; verify each location. This overview has no downloaded street tiles. Map/route data © OpenStreetMap contributors, ODbL; routing by OSRM where saved.</small></p></section>${plan.days.map(d=>`<section><h2>Day ${d.day} · ${esc(d.date)}</h2><h3>${esc(d.title)}</h3>${d.activities.map(a=>`<article><strong>${esc(a.time)}–${esc(a.endTime)} · ${esc(a.name)}</strong><p>${esc(a.description)}</p><small>${esc(a.location)} · Estimated group cost INR ${a.estimatedCost}</small>${a.adaptationReason?`<p class="notice">${esc(a.adaptationReason)}</p>`:''}</article>`).join('')}</section>`).join('')}<section><h2>Nearby places saved with this plan</h2>${(plan.nearby?.places||[]).slice(0,50).map(p=>`<p><strong>${esc(p.name)}</strong> · ${esc(p.kind)}<br><small>${p.latitude.toFixed(5)}, ${p.longitude.toFixed(5)}${p.phone?` · ${esc(p.phone)}`:''} · ${p.distanceKm} km from ${esc(p.nearStop)}</small></p>`).join('')||'<p>No nearby listings were saved.</p>'}</section><section><h2>Packing & notes</h2><ul>${[...plan.packingSuggestions,...(plan.warnings||[])].map(t=>`<li>${esc(t)}</li>`).join('')}</ul></section></html>`;}
export function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function downloadOffline(plan:Itinerary){let roads:Record<string,RoadRoute>={};try{roads=JSON.parse(localStorage.getItem('travelsetu_road_routes')||'{}');}catch{}downloadBlob(new Blob([offlineHtml(plan,roads)],{type:'text/html'}),`${plan.destination}-offline-trip.html`);}
export async function downloadPdf(plan:Itinerary){const {jsPDF}=await import('jspdf');const pdf=new jsPDF();let y=20;const clean=(text:string)=>text.replace(/₹/g,'INR ').replace(/[–—]/g,'-').replace(/[’‘]/g,"'");const line=(text:string,size=11)=>{pdf.setFontSize(size);const rows=pdf.splitTextToSize(clean(text),175);for(const row of rows){if(y>275){pdf.addPage();y=20;}pdf.text(row,18,y);y+=size*.5+2;}};line('TRAVELSETU | '+plan.destination,20);line(`${plan.startDate} to ${plan.endDate} | ${plan.travellers} travellers`);line('Saved itinerary. Recheck weather, road closures and official alerts before travel.');y+=5;line('Emergency contacts',15);for(const c of emergency)line(`${c.name}: ${c.number}`);for(const d of plan.days){y+=7;line(`Day ${d.day} | ${d.date} | ${d.title}`,15);for(const a of d.activities){line(`${a.time}-${a.endTime} ${a.name}`,12);line(a.description,10);line(`Estimated group cost: INR ${a.estimatedCost}`,10);y+=3;}}line(`Estimated trip total including reserve: INR ${plan.estimatedCost}`,12);pdf.save(`${plan.destination}-itinerary.pdf`);}
