import {z} from 'zod';
export const routePointSchema=z.object({latitude:z.number().finite().min(-90).max(90),longitude:z.number().finite().min(-180).max(180)});
export type RoutePoint=z.infer<typeof routePointSchema>;
export type RoadRoute={coordinates:[number,number][];distanceKm:number;durationMinutes:number;legs:{distanceKm:number;minutes:number}[];source:'OSRM';checkedAt:string;message:string};
export const routeKey=(points:RoutePoint[])=>points.map(p=>`${p.longitude.toFixed(5)},${p.latitude.toFixed(5)}`).join(';');
const cache=new Map<string,{until:number;route:RoadRoute}>();
export async function roadRoute(input:RoutePoint[],http:typeof fetch=fetch):Promise<RoadRoute>{const points=z.array(routePointSchema).min(2).max(30).parse(input),key=routeKey(points),saved=cache.get(key);if(http===fetch&&saved&&saved.until>Date.now())return saved.route;
 const configured=process.env.OSRM_BASE_URL||'https://router.project-osrm.org';const base=new URL(configured);if(base.protocol!=='https:'&&base.hostname!=='localhost'&&base.hostname!=='127.0.0.1')throw new Error('OSRM endpoint must use HTTPS.');const url=new URL(`${base.toString().replace(/\/$/,'')}/route/v1/driving/${key}`);url.searchParams.set('overview','simplified');url.searchParams.set('geometries','geojson');url.searchParams.set('steps','false');
 const r=await http(url.toString(),{signal:AbortSignal.timeout(8000),cache:'no-store'});if(!r.ok)throw new Error('Road routing unavailable');const body=await r.json(),a=body.routes?.[0];if(body.code!=='Ok'||!a||!Number.isFinite(a.duration)||!Number.isFinite(a.distance)||a.distance<0||a.duration<0||!Array.isArray(a.geometry?.coordinates)||!Array.isArray(a.legs)||a.legs.length!==points.length-1||a.legs.some((l:{distance:number;duration:number})=>!Number.isFinite(l.distance)||!Number.isFinite(l.duration)||l.distance<0||l.duration<0))throw new Error('No usable road route returned');
 const coordinates=a.geometry.coordinates.filter((p:unknown)=>Array.isArray(p)&&p.length>=2&&p.every(Number.isFinite)&&p[0]>=-180&&p[0]<=180&&p[1]>=-90&&p[1]<=90).slice(0,10000) as [number,number][];if(coordinates.length<2)throw new Error('No usable route geometry');const route:RoadRoute={coordinates,distanceKm:a.distance/1000,durationMinutes:Math.ceil(a.duration/60),legs:a.legs.map((l:{distance:number;duration:number})=>({distanceKm:l.distance/1000,minutes:Math.ceil(l.duration/60)})),source:'OSRM',checkedAt:new Date().toISOString(),message:'OSRM driving estimate from OpenStreetMap road data. No live traffic, current closures or turn-by-turn safety guarantee.'};if(http===fetch){if(cache.size>=100)cache.delete(cache.keys().next().value!);cache.set(key,{until:Date.now()+3600000,route});}return route;
}
