'use client';
import {create} from 'zustand';
import type {Itinerary} from './itinerary';
import type {TripForm} from '../types/travel';
import type {TripRecord,Expense} from './journal';
import {recordKey,expenseSchema} from './journal';
import {defaultTrip} from './trip';
const key='travelsetu_journal_v1';
type State={records:TripRecord[];activeId:string|null;hydrated:boolean;userId:string|null;notice:string;hydrate:()=>void;capture:(plan:Itinerary,trip?:TripForm)=>string;change:(id:string,patch:Partial<TripRecord>)=>void;addExpense:(id:string,expense:Expense)=>void;setUser:(id:string|null)=>void;markSynced:(id:string,ownerId:string,snapshotUpdatedAt:string,cloudVersion:number)=>void;merge:(records:TripRecord[])=>void};
const persist=(records:TripRecord[])=>{try{localStorage.setItem(key,JSON.stringify(records));return true;}catch{return false;}};
export const useTravelStore=create<State>((set,get)=>({records:[],activeId:null,hydrated:false,userId:null,notice:'',hydrate(){if(get().hydrated)return;try{const value=JSON.parse(localStorage.getItem(key)||'[]');set({records:Array.isArray(value)?value:[],hydrated:true});}catch{set({hydrated:true,notice:'Saved trip journal could not be loaded.'});}},capture(plan,trip){get().hydrate();const old=get().records.find(r=>recordKey(r.itinerary)===recordKey(plan)&&(!r.ownerId||r.ownerId===get().userId));const id=old?.id||crypto.randomUUID();const preferences=trip||old?.preferences||{...defaultTrip(),destination:plan.destination,from:plan.from,startDate:plan.startDate,endDate:plan.endDate,travellers:plan.travellers,budget:plan.budgetLimit||plan.estimatedCost};const record:TripRecord={id,preferences,itinerary:plan,expenses:old?.expenses||[],visited:old?.visited||[],reflection:old?.reflection||'',completed:old?.completed||false,photos:old?.photos||[],ownerId:old?.ownerId,cloudVersion:old?.cloudVersion,updatedAt:new Date().toISOString(),pendingSync:true};const records=[record,...get().records.filter(r=>r.id!==id)].slice(0,60);const saved=persist(records);set({records,activeId:id,notice:saved?'':'Browser storage is full. Download the trip to keep a copy.'});return id;},change(id,patch){const records=get().records.map(r=>r.id===id?{...r,...patch,id:r.id,updatedAt:new Date().toISOString(),pendingSync:true}:r);set({records,notice:persist(records)?'':'Could not save changes locally.'});},addExpense(id,expense){const parsed=expenseSchema.parse(expense);const record=get().records.find(r=>r.id===id);if(record)get().change(id,{expenses:[parsed,...record.expenses.filter(e=>e.id!==parsed.id)]});},markSynced(id,ownerId,snapshotUpdatedAt,cloudVersion){const records=get().records.map(r=>r.id===id?{...r,ownerId,cloudVersion,pendingSync:r.updatedAt!==snapshotUpdatedAt}:r);persist(records);set({records});},setUser(userId){set({userId});},merge(incoming){const combined=new Map(get().records.map(r=>[r.id,r]));for(const r of incoming){const local=combined.get(r.id);if(!local||!local.pendingSync&&local.updatedAt<r.updatedAt)combined.set(r.id,r);}const records=[...combined.values()];persist(records);set({records});}}));
export function rememberItinerary(plan:Itinerary){let trip:TripForm|undefined;try{trip=JSON.parse(localStorage.getItem('travelsetu_trip')||'null')||undefined;localStorage.setItem('travelsetu_itinerary',JSON.stringify(plan));}catch{}useTravelStore.getState().capture(plan,trip);window.dispatchEvent(new Event('travelsetu-plan-updated'));}
