'use client';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import {Suspense,useEffect,useMemo,useState} from 'react';
import {useSearchParams} from 'next/navigation';
import {LocateFixed,SlidersHorizontal,CloudSun} from 'lucide-react';
import destinations from '@/data/destinations.json';
import catalog from '@/data/places.json';
import {MAP_CATEGORIES,type MapPoint,type MapCategory} from '@/lib/map';
import {distanceKm,type Itinerary} from '@/lib/itinerary';
import LiveSafetyPanel from '@/app/components/LiveSafetyPanel';
import {useTripTracker} from '@/lib/use-trip-tracker';
import {trackDistance,directionsUrl} from '@/lib/tracking';
import {recordKey} from '@/lib/journal';
import WeatherDashboard from '@/app/components/WeatherDashboard';
import PlaceRating from '@/app/components/PlaceRating';
const TripMap=dynamic(()=>import('@/app/components/TripMap'),{ssr:false,loading:()=> <div className="panel grid h-[600px] place-items-center">Opening map…</div>});
function MapPageContent(){const params=useSearchParams();const [plan,setPlan]=useState<Itinerary|null>(null),[destinationId,setDestinationId]=useState('manali'),[day,setDay]=useState(1),[osm,setOsm]=useState<MapPoint[]>([]),[q,setQ]=useState(''),[radius,setRadius]=useState(10),[categories,setCategories]=useState<MapCategory[]>(MAP_CATEGORIES.map(c=>c.id)),[wheelchair,setWheelchair]=useState(false),[indoor,setIndoor]=useState(false),[hours,setHours]=useState(false),[planned,setPlanned]=useState(false),[maxCost,setMaxCost]=useState(5000),[nearRoute,setNearRoute]=useState(true),[selected,setSelected]=useState(''),[filters,setFilters]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[stamp,setStamp]=useState(''),[emergency,setEmergency]=useState<MapPoint[]>([]),[follow,setFollow]=useState(true),[stopName,setStopName]=useState('');
 const tracker=useTripTracker('travelsetu_track:'+ (plan?recordKey(plan):'explore'));
 const me:MapPoint|null=tracker.position?{id:'my-location',name:'Your GPS position',category:'destination',lat:tracker.position.latitude,lng:tracker.position.longitude,subtitle:`Accuracy ±${Math.round(tracker.position.accuracy)} m`,source:'device',detail:'Last GPS update '+new Date(tracker.position.timestamp).toLocaleTimeString('en-IN')}:null;
 const visited=useMemo<MapPoint[]>(()=>tracker.track.stops.map((p,i)=>({id:p.id,name:p.name,category:'destination',lat:p.latitude,lng:p.longitude,subtitle:'Visited '+new Date(p.timestamp).toLocaleString('en-IN'),source:'device',routeOrder:i+1})),[tracker.track.stops]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('travelsetu_itinerary')||'null');if(saved?.days){setPlan(saved);const d=destinations.find(d=>d.name===saved.destination);if(d)setDestinationId(d.id);}}catch{}},[]);
 useEffect(()=>{const lat=Number(params.get('lat')),lng=Number(params.get('lng')),name=params.get('name');if(params.has('lat')&&params.has('lng')&&params.get('lat')?.trim()&&params.get('lng')?.trim()&&Number.isFinite(lat)&&Number.isFinite(lng)&&Math.abs(lat)<=90&&Math.abs(lng)<=180){setSelected(`query:${lat}:${lng}`);setOsm(old=>[...old,{id:`query:${lat}:${lng}`,name:name||'Selected place',category:'attraction',lat,lng,subtitle:'Selected place',detail:'Selected from TravelSetu.',source:'google-maps'}]);}},[params]);
 const destination=destinations.find(d=>d.id===destinationId)!,current=plan?.destination===destination.name?plan:null;
 const center=useMemo<[number,number]>(()=>[destination.latitude,destination.longitude],[destination]);
 const route=useMemo<MapPoint[]>(()=> (current?.days.find(d=>d.day===day)?.activities||[]).filter(a=>a.type==='activity'&&a.placeId&&Number.isFinite(a.latitude)&&Number.isFinite(a.longitude)).map((a,i)=>({id:a.placeId!,name:a.name,category:'attraction',lat:a.latitude!,lng:a.longitude!,subtitle:a.time+' · '+a.durationMinutes+' min',routeOrder:i+1,detail:a.description,source:current?.generation?'gemini':'catalog',cost:a.estimatedCost/(current?.travellers||1),indoor:a.indoor,accuracy:a.locationAccuracy||'Approximate catalog point'})),[current,day]);
 const all=useMemo(()=>{const base:MapPoint[]=current?[]:catalog.filter(p=>p.destinationId===destinationId).map(p=>({id:p.id,name:p.name,category:'attraction',lat:p.latitude,lng:p.longitude,subtitle:p.category,detail:p.visitTip,source:'catalog',cost:p.estimatedCost,indoor:p.indoor,accuracy:'Approximate catalog point'}));const nearby:MapPoint[]=(current?.nearby?.places||[]).map(p=>({id:p.id,name:p.name,category:p.kind==='experience'?'attraction':p.kind,lat:p.latitude,lng:p.longitude,subtitle:p.nearStop,detail:p.matchReason,source:'openstreetmap',sourceUrl:p.sourceUrl,openingHours:p.openingHours,phone:p.phone,wheelchair:p.wheelchair,accuracy:'OSM community listing'}));return [...new Map([...base,...nearby,...osm,...route].map(p=>[p.id,p])).values()];},[current,destinationId,osm,route]);
 const visible=useMemo(()=>{const measure=(p:MapPoint)=>nearRoute&&route.length?Math.min(...route.map(r=>distanceKm({latitude:r.lat,longitude:r.lng},{latitude:p.lat,longitude:p.lng}))):distanceKm(destination,{latitude:p.lat,longitude:p.lng});return all.filter(p=>categories.includes(p.category)&&(!q||[p.name,p.detail,p.category].join(' ').toLowerCase().includes(q.toLowerCase()))&&measure(p)<=radius&&(!wheelchair||p.wheelchair==='yes')&&(!indoor||p.indoor===true)&&(!hours||!!p.openingHours)&&(!planned||route.some(r=>r.id===p.id))&&(maxCost===5000||p.cost!==undefined&&p.cost<=maxCost)).sort((a,b)=>measure(a)-measure(b));},[all,categories,q,radius,wheelchair,indoor,hours,planned,route,maxCost,destination,nearRoute]);
 const selectedPoint=[...all,...emergency,...visited].find(p=>p.id===selected)||me,weather=current?.conditions?.weather.daily.find(w=>w.date===current.days.find(d=>d.day===day)?.date);
 async function nearby(){setBusy(true);try{const r=await fetch(`/api/places?destination=${destinationId}&radius=${Math.min(radius,10)}`,{signal:AbortSignal.timeout(25000)}),data=await r.json();if(!r.ok)throw new Error(data.error);setOsm(data.points);setStamp(data.fetchedAt);setMessage(data.points.length?'Nearby listings updated.':'No listings returned for this search.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 const mapPoints=useMemo(()=>[...new Map([...visible,...emergency.filter(p=>tracker.position&&distanceKm(tracker.position,{latitude:p.lat,longitude:p.lng})<=5),...visited].map(p=>[p.id,p])).values()],[visible,emergency,visited,tracker.position]);
 function selectPoint(id:string){setSelected(id);setFollow(false);}
 function locate(){tracker.start();setFollow(true);}
 return <main className="page-shell map-page"><div className="container-page"><div className="page-head"><div><h1 className="page-title">Trip map</h1><p className="text-sm muted">Your route, nearby places and the weather ahead.</p></div><div className="page-actions"><button className="btn-secondary" onClick={locate}><LocateFixed size={17}/>{tracker.active?'Recording GPS':'Start GPS tracking'}</button><button className="btn-secondary" aria-expanded={filters} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={16}/>Filters</button><Link className="btn-primary" href="/itinerary">My itinerary</Link></div></div>
 <div className="mt-6 flex flex-wrap items-center gap-3"><select className="rounded-lg border bg-white px-3 py-2 text-sm" aria-label="Destination" value={destinationId} onChange={e=>{setDestinationId(e.target.value);setOsm([]);setSelected('');setStamp('');}}>{destinations.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select>{current&&<select className="rounded-lg border bg-white px-3 py-2 text-sm" aria-label="Itinerary day" value={day} onChange={e=>setDay(+e.target.value)}>{current.days.map(d=><option value={d.day} key={d.day}>Day {d.day} · {d.date}</option>)}</select>}<span className="text-sm muted">{visible.length} places on the map</span></div>
 {filters&&<section className="panel mt-5"><div className="grid gap-4 sm:grid-cols-3"><label><span className="label">Search places</span><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Name or category"/></label><label><span className="label">Radius · {radius} km</span><input className="mt-5 w-full accent-green-800" type="range" min={1} max={50} value={radius} onChange={e=>setRadius(+e.target.value)}/></label><label><span className="label">Entry estimate / person</span><select className="input" value={maxCost} onChange={e=>setMaxCost(+e.target.value)}>{[[5000,'Any / unknown'],[0,'Free estimate'],[200,'Up to ₹200'],[500,'Up to ₹500'],[1000,'Up to ₹1,000']].map(([v,t])=><option value={v} key={v}>{t}</option>)}</select></label></div><div className="mt-5 flex flex-wrap gap-2">{MAP_CATEGORIES.map(c=><button key={c.id} className="chip" aria-pressed={categories.includes(c.id)} onClick={()=>setCategories(old=>old.includes(c.id)?old.filter(x=>x!==c.id):[...old,c.id])}>{c.label}</button>)}</div><div className="mt-5 flex flex-wrap gap-5 text-sm">{[['Near day stops',nearRoute,setNearRoute],['Wheelchair tagged',wheelchair,setWheelchair],['Indoors',indoor,setIndoor],['Hours listed',hours,setHours],['Planned stops',planned,setPlanned]].map(([label,value,set])=><label className="flex gap-2" key={String(label)}><input type="checkbox" checked={Boolean(value)} onChange={e=>(set as (v:boolean)=>void)(e.target.checked)}/>{String(label)}</label>)}</div><button className="mt-5 text-sm font-semibold text-[#075b3d]" onClick={()=>{setQ('');setRadius(10);setCategories(MAP_CATEGORIES.map(c=>c.id));setWheelchair(false);setIndoor(false);setHours(false);setPlanned(false);setMaxCost(5000);}}>Reset filters</button><button className="btn-secondary ml-4" disabled={busy} onClick={nearby}>{busy?'Loading…':'Load destination places'}</button>{stamp&&<p className="mt-2 text-xs muted">Updated {new Date(stamp).toLocaleTimeString()}</p>}</section>}
 <section className="panel mt-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold">Your trip in motion</h2><p className="mt-1 text-sm muted">{trackDistance(tracker.track.points).toFixed(2)} km · {Math.floor(tracker.track.elapsedSeconds/60)} min recorded · {tracker.track.stops.length} marked visits</p></div><div className="flex flex-wrap gap-3"><button className="btn-primary" onClick={tracker.active?tracker.stop:locate}>{tracker.active?'Pause recording':'Start / resume'}</button><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={follow} onChange={e=>setFollow(e.target.checked)}/>Follow my position</label></div></div><div className="mt-4 flex flex-wrap gap-2"><input className="input max-w-xs" aria-label="Name of visited stop" placeholder="Name this visited stop (optional)" value={stopName} maxLength={100} onChange={e=>setStopName(e.target.value)}/><button className="btn-secondary" disabled={!tracker.position} onClick={()=>{tracker.markStop(stopName);setStopName('');}}>Mark this visit</button></div><p role="status" className="mt-3 text-xs muted">{tracker.message||'Recording starts only when you choose. Your browser will ask for location access.'}</p><details className="mt-3 text-xs muted"><summary>Recording details</summary><p className="mt-2">Keep this page open. Screen locks, GPS gaps and background browser limits can interrupt recording. Pauses are not joined by imaginary route segments. Save your route image before clearing.</p><button className="mt-3 text-red-700 underline" onClick={()=>{if(window.confirm('Clear the recorded route and marked visits from this device?'))tracker.reset();}}>Clear saved recording</button></details></section>
 <div className="mt-5 grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_285px]"><section className="min-w-0"><TripMap center={center} points={mapPoints} position={tracker.position} track={tracker.track} follow={follow} tripName={plan?`${plan.destination} trip`:destination.name} route={route} selectedId={selected} onSelect={p=>selectPoint(p.id)}/>{message&&<p role="status" className="mt-3 text-sm muted">{message}</p>}{selectedPoint&&<section className="panel mt-5"><div className="flex justify-between gap-4"><div><h2 className="text-lg font-semibold">{selectedPoint.name}</h2><p className="mt-1 text-xs muted">{selectedPoint.accuracy}</p></div><a className="btn-secondary h-fit" href={directionsUrl({latitude:selectedPoint.lat,longitude:selectedPoint.lng},tracker.position&&Date.now()-tracker.position.timestamp<60000?tracker.position:undefined)} target="_blank" rel="noreferrer">Directions <span aria-hidden="true">↗</span></a></div><details className="mt-4 text-sm"><summary>Place details</summary><p className="mt-3 detail-copy">{selectedPoint.detail}</p><div className="mt-4 grid gap-2 text-xs muted sm:grid-cols-2"><p>Hours: {selectedPoint.openingHours||'Not listed'}</p><p>Access: {selectedPoint.wheelchair||'Not verified'}</p><p>Phone: {selectedPoint.phone||'Not listed'}</p>{selectedPoint.sourceUrl&&<a href={selectedPoint.sourceUrl} target="_blank" rel="noreferrer">View source ↗</a>}</div></details>{(['hotel','restaurant','attraction'].includes(selectedPoint.category)||visited.some(p=>p.id===selectedPoint.id))&&<details className="mt-4 text-sm"><summary>Ratings & reviews</summary><PlaceRating id={selectedPoint.id} name={selectedPoint.name} kind={selectedPoint.category==='hotel'?'hotel':selectedPoint.category==='restaurant'?'restaurant':'attraction'} latitude={selectedPoint.lat} longitude={selectedPoint.lng}/></details>}</section>}<details className="quiet-details mt-5"><summary>All matching places ({visible.length})</summary><div className="grid max-h-80 gap-2 overflow-auto sm:grid-cols-2">{visible.map(p=><button className="rounded-lg border p-3 text-left text-sm" key={p.id} onClick={()=>selectPoint(p.id)}>{p.name}<span className="mt-1 block text-xs muted">{p.category}</span></button>)}</div></details></section>
 <aside className="space-y-5"><section className="panel"><div className="flex items-center justify-between gap-2"><h2 className="font-semibold">Trip stops</h2><span className="text-xs muted">Day {day}</span></div><div className="mt-4 divide-y">{route.map((p,i)=><button className="flex w-full items-center gap-3 py-4 text-left" key={p.id} onClick={()=>selectPoint(p.id)}><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full bg-[#075b3d] text-xs text-white">{i+1}</span><span className="min-w-0 text-sm font-medium">{p.name}<small className="mt-1 block text-xs font-normal muted">{p.subtitle}</small></span></button>)}{!route.length&&<p className="py-4 text-sm muted">No mapped sightseeing stops for this day.</p>}</div><Link href="/itinerary" className="mt-3 block text-sm font-semibold text-[#075b3d]">View day plan →</Link></section><LiveSafetyPanel position={tracker.position} onPoints={setEmergency} onSelect={selectPoint}/><WeatherDashboard destination={destination.name} compact/></aside></div></div></main>;
}

export default function MapPage(){return <Suspense fallback={<div className="panel">Loading your map…</div>}><MapPageContent/></Suspense>;}
