"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Heart, Search, SlidersHorizontal, Shuffle, X, Compass, MapPin, Check } from "lucide-react";
import DiscoveryHub,{MoodTiles} from '@/app/components/DiscoveryHub';
import CuisineDiscovery from '@/app/components/CuisineDiscovery';
import data from "@/data/destinations.json";
import { formatINR } from "@/lib/trip";
const months=["Any month","January","February","March","April","May","June","July","August","September","October","November","December"];
const interests=["All","Mountains","Beaches","Culture","Nature","Food","Spiritual","Wildlife","Romantic","Adventure"];
export default function ExplorePage(){
 const [showAll,setShowAll]=useState(false);const [q,setQ]=useState(""); const [interest,setInterest]=useState("All"); const [region,setRegion]=useState("All regions"); const [month,setMonth]=useState(0);const [maxBudget,setMaxBudget]=useState(5000);const [savedOnly,setSavedOnly]=useState(false);const [favourites,setFavourites]=useState<string[]>([]);const [compare,setCompare]=useState<string[]>([]);const [discovery,setDiscovery]=useState(false);const [days,setDays]=useState(0);const [sort,setSort]=useState("recommended");const [message,setMessage]=useState("");
 useEffect(()=>{const p=new URLSearchParams(window.location.search);setQ(p.get('q')||p.get('destination')||'');const i=p.get('interest');if(i&&interests.includes(i))setInterest(i);setDiscovery(p.has('discover'));try{const stored=JSON.parse(localStorage.getItem('travelsetu_favourites')||'[]');if(Array.isArray(stored))setFavourites(stored.filter(x=>typeof x==='string'));}catch{}},[]);
 const filtered=useMemo(()=>data.filter(d=>(!q||[d.name,d.state,...d.activities,...d.localFood].join(' ').toLowerCase().includes(q.toLowerCase()))&&(interest==='All'||d.category.includes(interest))&&(region==='All regions'||d.region===region)&&(!month||d.bestMonths.includes(month))&&d.dailyBudget<=maxBudget&&(!savedOnly||favourites.includes(d.id))&&(!days||d.idealDays<=days)).sort((a,b)=>sort==='budget'?a.dailyBudget-b.dailyBudget:sort==='name'?a.name.localeCompare(b.name):a.idealDays-b.idealDays),[q,interest,region,month,maxBudget,savedOnly,favourites,days,sort]);
 function favourite(id:string){const next=favourites.includes(id)?favourites.filter(x=>x!==id):[...favourites,id];setFavourites(next);try{localStorage.setItem('travelsetu_favourites',JSON.stringify(next));}catch{setMessage('Your browser could not save favourites.');}}
 function toggleCompare(id:string){setCompare(v=>v.includes(id)?v.filter(x=>x!==id):v.length<3?[...v,id]:v);}
 function reset(){setQ('');setInterest('All');setRegion('All regions');setMonth(0);setMaxBudget(5000);setSavedOnly(false);setDays(0);}
 return <main className="page-shell"><div className="container-page">
  <div className="flex flex-wrap items-start justify-between gap-6"><div><p className="eyebrow">Find your corner of India</p><h1 className="page-title">Explore India.</h1><p className="max-w-2xl muted">{data.length} destinations. Find one that feels like you.</p></div><button onClick={()=>setDiscovery(!discovery)} className="btn-yellow"><Compass size={18}/>{discovery?'Close trip finder':'Help me choose'}</button></div>
  <nav className="discovery-nav" aria-label="Explore collections"><a href="#destinations">Destinations</a><a href="#cuisines">Culinary delights</a><a href="#local-craft">Local crafts</a><a href="#india-notebook">India notebook</a></nav>
  <MoodTiles active={interest} onChoose={value=>{setInterest(value);setShowAll(false);document.getElementById('destinations')?.scrollIntoView({behavior:'smooth'});}}/>
  {discovery&&<section className="panel mt-8 border-blue-200 bg-[#edf5ec]"><h2 className="text-xl font-bold">A few clues to your next escape</h2><p className="mt-2 text-sm muted">Pick a mood below, set your month and budget, and choose how long you have.</p><div className="mt-4 flex flex-wrap items-center gap-3"><span className="font-semibold">I have</span>{[2,3,4,5,7].map(n=><button key={n} className="chip" aria-pressed={days===n} onClick={()=>setDays(days===n?0:n)}>{n} days</button>)}<button className="btn-primary" disabled={!filtered.length} onClick={()=>{const d=filtered[Math.floor(Math.random()*filtered.length)];if(d)window.location.href=`/explore/${d.id}`;}}><Shuffle size={16}/> Surprise me</button></div></section>}
  <section className="panel mt-8" id="destinations"><div className="flex items-center gap-2 text-sm font-bold"><SlidersHorizontal size={17}/> Make it your kind of trip</div><div className="mt-5 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
   <label><span className="label">Place, state, food or sight</span><div className="relative"><Search size={18} className="pointer-events-none absolute left-3 top-6 text-slate-400"/><input className="input pl-10" placeholder="Try Kerala, forts, tea…" value={q} onChange={e=>setQ(e.target.value)}/></div></label>
   <label><span className="label">Region</span><select className="input" value={region} onChange={e=>setRegion(e.target.value)}>{['All regions','North','South','East','West','Central','Northeast','Islands'].map(x=><option key={x}>{x}</option>)}</select></label>
   <label><span className="label">When would you go?</span><select className="input" value={month} onChange={e=>setMonth(Number(e.target.value))}>{months.map((m,i)=><option key={m} value={i}>{m}</option>)}</select></label>
   <label><span className="label">Daily budget / person · {formatINR(maxBudget)}</span><input type="range" min={1000} max={5000} step={100} value={maxBudget} onChange={e=>setMaxBudget(Number(e.target.value))} className="mt-7 w-full accent-[#075b3d]"/></label>
  </div><div className="mt-6 flex flex-wrap gap-2">{interests.map(x=><button key={x} className="chip" aria-pressed={interest===x} onClick={()=>setInterest(x)}>{x}</button>)}</div><details className="mt-5 text-xs muted"><summary>About budget & season estimates</summary><p className="mt-2">Budget estimates cover food, a shared basic stay and local sightseeing. Intercity travel is extra. Seasonal guides are not forecasts.</p></details></section>
  <div className="my-6 flex flex-wrap items-center justify-between gap-4"><p aria-live="polite" className="font-bold">{filtered.length} places to spark an idea</p><div className="flex flex-wrap items-center gap-3"><button className="chip" aria-pressed={savedOnly} onClick={()=>setSavedOnly(!savedOnly)}><Heart size={15}/> Saved ({favourites.length})</button><label className="text-sm">Sort <select className="ml-2 rounded-lg border bg-white p-2" value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Short escapes first</option><option value="budget">Lowest daily estimate</option><option value="name">A–Z</option></select></label><button className="text-sm font-bold text-[#075b3d]" onClick={reset}>Reset filters</button></div></div>
  {message&&<p role="status" className="notice mb-5">{message}</p>}
  {!filtered.length?<div className="panel py-16 text-center"><h2 className="text-xl font-bold">A small change could open up more places.</h2><p className="mt-3 muted">Try another month, a larger budget or fewer filters.</p><button onClick={reset} className="btn-primary mt-5">Show all destinations</button></div>:<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{(showAll?filtered:filtered.slice(0,9)).map(d=><article key={d.id} className="overflow-hidden rounded-3xl border border-[#e0e8f1] bg-white shadow-sm"><div className={`relative ${d.image?'h-44':'bg-[#063e2b] py-6'} overflow-hidden`}>{d.image&&<img className="h-full w-full object-cover" src={d.image} alt={d.name} loading="lazy"/>}<span className={`${d.image?'absolute left-4 top-4':'ml-5'} inline-flex items-center gap-1 rounded-full bg-white px-3 py-1 text-xs font-bold text-[#294866]`}><MapPin size={13}/>{d.region} India</span><button aria-label={`${favourites.includes(d.id)?'Unsave':'Save'} ${d.name}`} aria-pressed={favourites.includes(d.id)} onClick={()=>favourite(d.id)} className="absolute right-4 top-4 rounded-full bg-white p-2.5 text-[#075b3d]"><Heart size={18} fill={favourites.includes(d.id)?'currentColor':'none'}/></button></div><div className="p-6"><p className="eyebrow text-xs">{d.state}</p><h2 className="mt-1 text-2xl font-bold"><Link href={`/explore/${d.id}`}>{d.name}</Link></h2><details className="mt-3 text-sm muted"><summary>What makes it special</summary><p className="mt-3 leading-6">{d.description}</p></details><div className="my-4 grid grid-cols-2 gap-3 border-y border-slate-100 py-4 text-sm"><div><span className="block text-xs muted">A good first visit</span><strong>{d.idealDays} days</strong></div><div><span className="block text-xs muted">From / person / day</span><strong>{formatINR(d.dailyBudget)}</strong></div></div><p className="text-sm muted"><strong className="text-[#203b58]">Go for:</strong> {d.activities.slice(0,2).join(' · ')}</p><div className="mt-5 flex items-center justify-between gap-2"><Link href={`/explore/${d.id}`} className="text-sm font-bold text-[#075b3d]">See the destination <ArrowRight className="inline" size={15}/></Link><button onClick={()=>toggleCompare(d.id)} aria-pressed={compare.includes(d.id)} disabled={compare.length>=3&&!compare.includes(d.id)} className="chip px-3 text-xs">{compare.includes(d.id)?<Check size={14}/>:null}Compare</button></div></div></article>)}</div>}
  {filtered.length>9&&<div className="text-center mt-7"><button className="btn-secondary" onClick={()=>setShowAll(!showAll)}>{showAll?'Show fewer destinations':`Explore all ${filtered.length} destinations`}<ArrowRight size={16}/></button></div>}
  {compare.length>0&&<section className="panel mt-8 border-blue-200"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Compare your shortlist ({compare.length}/3)</h2><button onClick={()=>setCompare([])} aria-label="Clear comparison"><X size={20}/></button></div><div className="mt-5 overflow-auto"><table className="w-full min-w-[520px] text-left text-sm"><thead><tr><th className="p-3">Your trip</th>{compare.map(id=><th key={id} className="p-3 text-lg">{data.find(d=>d.id===id)?.name}</th>)}</tr></thead><tbody>{['Good first visit','Daily estimate / person','Best months','Local food'].map((label,i)=><tr key={label} className="border-t"><th className="p-3">{label}</th>{compare.map(id=>{const d=data.find(d=>d.id===id)!;return <td key={id} className="p-3">{[`${d.idealDays} days`,formatINR(d.dailyBudget),d.bestTime,d.localFood.join(', ')][i]}</td>})}</tr>)}<tr><th/><>{compare.map(id=><td key={id} className="p-3"><Link className="btn-primary" href={`/plan-trip?destination=${encodeURIComponent(data.find(d=>d.id===id)!.name)}`}>Plan this trip</Link></td>)}</></tr></tbody></table></div></section>}
 <CuisineDiscovery/><div><DiscoveryHub/></div>
 </div></main>
}
