import destinations from '../../data/destinations.json';
import hotels from '../../data/hotels.json';
import trains from '../../data/trains.json';
import { isDate, minutes } from '../trip-validation';
import { todayDate, getTripDuration, getTripNights } from '../trip';
import type { BookingSearch, BookingOffer } from './types';
export function parseSearch(input:unknown):BookingSearch{
 if(!input||typeof input!=='object')throw new Error('Booking search details are required.');const x=input as Record<string,unknown>;
 if(!['hotel','restaurant','vehicle','bus','train','flight'].includes(String(x.kind)))throw new Error('Choose a booking type.');
 const kind=x.kind as BookingSearch['kind'],mode=x.mode==='test'?'test':'demo',destinationId=String(x.destinationId||'');
 if(!destinations.some(d=>d.id===destinationId))throw new Error('Select a destination.');
 const checkIn=String(x.checkIn||''),checkOut=String(x.checkOut||'');if(!isDate(checkIn)||!isDate(checkOut)||getTripDuration(checkIn,checkOut)<1||getTripDuration(checkIn,checkOut)>31)throw new Error('Choose valid dates, up to 31 days apart.');if(kind==='hotel'&&!getTripNights(checkIn,checkOut))throw new Error('Hotel checkout must be after check-in.');
 if(mode==='test'&&checkIn<todayDate())throw new Error('Supplier searches need current or future dates.');
 const rooms=Number(x.rooms||1),adults=Number(x.adults||1);if(!Number.isInteger(rooms)||rooms<1||rooms>5||!Number.isInteger(adults)||adults<1||adults>(kind==='hotel'?4:20))throw new Error('Check the room and adult counts.');
 const childrenAges=Array.isArray(x.childrenAges)?x.childrenAges.map(Number):[];if(childrenAges.length>4||childrenAges.some(a=>!Number.isInteger(a)||a<0||a>17))throw new Error('Enter child ages from 0 to 17.');
 const budgetLimit=x.budgetLimit===undefined?undefined:Number(x.budgetLimit);if(budgetLimit!==undefined&&(!Number.isFinite(budgetLimit)||budgetLimit<1||budgetLimit>10000000))throw new Error('Enter a booking allowance from ₹1 to ₹1,00,00,000.');
 const pickupTime=String(x.pickupTime||'10:00');minutes(pickupTime);
 const query:BookingSearch={kind,mode,destinationId,from:String(x.from||'Delhi').slice(0,80),checkIn,checkOut,rooms:kind==='hotel'?rooms:1,adults,childrenAges,pickupTime,...(budgetLimit!==undefined?{budgetLimit}:{})};
 if(x.latitude!==undefined||x.longitude!==undefined){const latitude=Number(x.latitude),longitude=Number(x.longitude),d=destinations.find(d=>d.id===destinationId)!;if(!Number.isFinite(latitude)||!Number.isFinite(longitude)||Math.abs(latitude-d.latitude)>1||Math.abs(longitude-d.longitude)>1)throw new Error('Choose a search area near the destination.');query.latitude=latitude;query.longitude=longitude;query.areaName=String(x.areaName||'Selected area').slice(0,160);}
 const radius=Number(x.radiusKm||3);if(!Number.isFinite(radius)||radius<1||radius>10)throw new Error('Choose a radius from 1 to 10 km.');query.radiusKm=radius;
 if(kind==='vehicle'&&mode==='test'){const airport=String(x.pickupAirport||'').toUpperCase(),hotel=String(x.dropoffHotel||'');if(!/^[A-Z]{3}$/.test(airport)||!/^\d{1,10}$/.test(hotel))throw new Error('Choose an airport and a supplier hotel for the transfer.');query.pickupAirport=airport;query.dropoffHotel=hotel;}
 if(mode==='test'&&(kind==='bus'||kind==='train'||kind==='flight'))throw new Error('Bus, train and flight listings are available in demo mode only.');return query;
}
export function demoOffers(q:BookingSearch):BookingOffer[]{const d=destinations.find(d=>d.id===q.destinationId)!;const people=(q.adults+q.childrenAges.length)*q.rooms,nights=getTripNights(q.checkIn,q.checkOut),days=getTripDuration(q.checkIn,q.checkOut);
 const base={kind:q.kind,mode:'demo' as const,provider:'TravelSetu sample inventory',currency:'INR',query:q,cancellation:['Sample reservation can be removed locally. No supplier cancellation is made.'],terms:'Demonstration only. Prices, amenities and availability are fictional; no payment or real reservation occurs.'};
 if(q.kind==='hotel')return ['Budget stay','Comfort hotel','Boutique retreat','Backpacker hostel','Family homestay','Serviced apartment','Heritage-style stay','Premium hotel'].map((type,i)=>{const local=hotels.filter(h=>h.destinationId===q.destinationId)[i];const rate=local?.pricePerNight||Math.round(d.dailyBudget*(.7+i*.55)/100)*100;return {...base,id:`demo-${d.id}-hotel-${i}`,name:`Sample ${type} · ${d.name}`,price:rate*nights*q.rooms,priceLabel:`${nights} nights × ${q.rooms} rooms · total`,description:`${q.adults} adults${q.childrenAges.length?` + ${q.childrenAges.length} children`:''} per room. Room rates are sample values.`,amenities:[...new Set(['Wi-Fi',...(local?.amenities||[]),...(i>0?['Breakfast','Air conditioning']:[]),...(i===2?['Pool','Parking']:[])])],stars:Math.min(5,i+2),image:local?.image,capacity:people};});
 if(q.kind==='restaurant'){
   const restaurants=require('../../data/restaurants.json') as typeof import('../../data/restaurants.json');
   return restaurants.filter(r=>r.destinationId===q.destinationId).map((r,i)=>({...base,id:r.id,name:r.name,price:r.averageCost*people,priceLabel:`${people} diners · sample reservation total`,description:`${r.area} · ${r.cuisine} · Popular: ${r.popularDishes.join(', ')}. Demo reservation created inside TravelSetu.`,amenities:[r.cuisine,r.vegetarianFriendly?'Vegetarian friendly':'Ask about dietary options'],image:r.image,capacity:people}));
 }
 if(q.kind==='vehicle')return [{name:'Economy hatchback · self-drive',capacity:4,rate:940,features:['Basic compact car','Driving licence required','Sample allowance']},{name:'Scooter · self-drive',capacity:2,rate:650,features:['Helmet','Driving licence required']},{name:'Sedan · with driver',capacity:4,rate:2400,features:['Air conditioning','Driver','2 bags']},{name:'SUV · with driver',capacity:6,rate:3600,features:['Air conditioning','Driver','3 bags']},{name:'Minibus · with driver',capacity:12,rate:6500,features:['Air conditioning','Driver','Group travel']},{name:'Hatchback · self-drive',capacity:4,rate:1800,features:['Driving licence required','Fuel extra']},{name:'Electric sedan · with driver',capacity:4,rate:2900,features:['Driver','Charging stops need planning']},{name:'Premium MPV · with driver',capacity:7,rate:4800,features:['Driver','Family luggage space']},{name:'Tempo traveller · with driver',capacity:16,rate:8200,features:['Driver','Group travel']},{name:'Mini coach · with driver',capacity:20,rate:10500,features:['Driver','Large groups']}].filter(v=>v.capacity>=people).map((v,i)=>({...base,id:`demo-${d.id}-vehicle-${i}`,name:v.name,price:v.rate*days,priceLabel:`${days} local hire days · 1 vehicle · total`,description:`Sample local hire within ${d.name}, not a ${q.from}–${d.name} intercity fare. Fuel, tolls, parking and overtime need a separate quote.`,amenities:v.features,capacity:v.capacity}));
 if(q.kind==='bus'||q.kind==='train'){
   const source=(q.kind==='bus' ? (require('../../data/buses.json') as typeof import('../../data/buses.json')) : trains)
     .filter(x=>x.destinationId===q.destinationId && String(x.from).toLowerCase()===q.from.toLowerCase());
   return source.map((x,i)=>({...base,id:x.id,name:`${x.operator} · ${x.service}`,price:x.pricePerPerson*people,priceLabel:`${people} travellers · one-way sample total`,description:`${x.from} → ${x.to} · ${x.departure}–${x.arrival} · ${x.duration}. Demo inventory for website booking flow.`,amenities:[x.budgetTier==='budget'?'Budget fare':'Comfort fare',x.status],capacity:people}));
 }
 const names=['Economy flight','Flexible economy flight'];return names.map((n,i)=>({...base,id:`demo-${d.id}-flight-${i}`,name:`Sample ${n}`,price:(5200+i*1500)*people,priceLabel:`${people} travellers · one-way sample total`,description:`${q.from} → ${d.name}. Demo flight inventory for the TravelSetu website booking flow.`,amenities:['Cabin baggage','Economy'],capacity:people}));
}
