import { createHash } from 'node:crypto';
import destinations from '../../data/destinations.json';
import type { BookingSearch, BookingOffer, BookingContact } from './types';
// This integration deliberately targets the supplier evaluation environment.
// Production checkout requires the supplier's certification plus authentication/payment operations.
const HOST='https://api.test.hotelbeds.com';
type Obj=Record<string,any>; // Untrusted supplier responses are validated at this boundary.
function price(value:unknown){const n=Number(value);if(!Number.isFinite(n)||n<0)throw new Error('Supplier returned an invalid price.');return n;}
function currency(value:unknown){if(!/^[A-Z]{3}$/.test(String(value)))throw new Error('Supplier currency is missing.');return String(value);}
export function supplierConfigured(kind:'hotel'|'vehicle'){const key=kind==='hotel'?'HOTELBEDS_HOTEL':'HOTELBEDS_TRANSFER';return !!(process.env[key+'_API_KEY']&&process.env[key+'_SECRET']);}
export async function hotelbedsRequest(kind:'hotel'|'vehicle',path:string,body?:unknown,fetcher:typeof fetch=fetch):Promise<Obj>{
 const prefix=kind==='hotel'?'HOTELBEDS_HOTEL':'HOTELBEDS_TRANSFER',key=process.env[prefix+'_API_KEY'],secret=process.env[prefix+'_SECRET'];if(!key||!secret)throw new Error('Supplier test credentials are not configured. Choose sample inventory or follow the API setup guide.');
 const signature=createHash('sha256').update(key+secret+Math.floor(Date.now()/1000)).digest('hex');
 const response=await fetcher(HOST+path,{method:body?'POST':'GET',headers:{'Api-key':key,'X-Signature':signature,Accept:'application/json','Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(22000),cache:'no-store'});
 if(!response.ok)throw new Error(response.status===401||response.status===403?'Supplier authentication failed. Check the matching Hotel/Transfer test credentials.':response.status===429?'Supplier rate limit reached. Please wait before searching again.':`Supplier request failed (${response.status}). Availability has not been confirmed.`);
 const data=await response.json();if(!data||typeof data!=='object'||data.error||data.errors)throw new Error('Supplier could not complete the request.');return data;
}
function cancellation(policies:unknown,fallbackCurrency:string){return Array.isArray(policies)&&policies.length?policies.map((p:Obj)=>`${p.amount} ${p.currencyId||fallbackCurrency} cancellation charge from ${p.from}${p.utcOffset?` (UTC${p.utcOffset})`:''}`):['No cancellation terms were returned; do not assume free cancellation.'];}
export function hotelPayload(q:BookingSearch){const d=destinations.find(d=>d.id===q.destinationId)!;return {stay:{checkIn:q.checkIn,checkOut:q.checkOut},occupancies:[{rooms:q.rooms,adults:q.adults,children:q.childrenAges.length,...(q.childrenAges.length?{paxes:q.childrenAges.map(age=>({type:'CH',age}))}:{})}],geolocation:{latitude:q.latitude??d.latitude,longitude:q.longitude??d.longitude,radius:q.radiusKm||3,unit:'km'},filter:{maxHotels:25,maxRatesPerRoom:2},language:'ENG'};}
function hotelOffer(h:Obj,r:Obj,rate:Obj,q:BookingSearch):BookingOffer{
 if(typeof rate.rateKey!=='string')throw new Error('Supplier rate is missing.');const c=currency(h.currency);
 return {id:`hb-hotel-${h.code}-${r.code}-${createHash("sha256").update(rate.rateKey).digest("hex").slice(0,10)}`,name:String(h.name),kind:'hotel',mode:'test',provider:'Hotelbeds evaluation API',price:price(rate.sellingRate??rate.net),currency:c,priceLabel:`${q.rooms} rooms · entire stay · supplier total`,description:`${r.name} · ${rate.boardName||'Board unspecified'} · ${h.categoryName||'Category unspecified'}`,amenities:rate.boardName?[String(rate.boardName)]:[],cancellation:cancellation(rate.cancellationPolicies,c),terms:String(rate.rateComments||'Rate conditions are refreshed before confirmation.')+(rate.taxes?.allIncluded?' Taxes included as reported by supplier.':' Additional local taxes or charges may apply; check supplier terms.'),stars:/^[1-5]EST$/.test(String(h.categoryCode))?Number(String(h.categoryCode)[0]):undefined,hotelCode:String(h.code),rateKey:rate.rateKey,rateType:String(rate.rateType),latitude:Number(h.latitude),longitude:Number(h.longitude),query:q};
}
export async function searchHotels(q:BookingSearch,fetcher:typeof fetch=fetch){const data=await hotelbedsRequest('hotel','/hotel-api/1.0/hotels',hotelPayload(q),fetcher);const out:BookingOffer[]=[];for(const h of data.hotels?.hotels||[])for(const room of h.rooms||[])for(const rate of room.rates||[]){if(Number(rate.rooms)!==q.rooms||Number(rate.adults)!==q.adults||Number(rate.children||0)!==q.childrenAges.length)continue;try{out.push(hotelOffer(h,room,rate,q));}catch{}}return out.slice(0,40);}
export function transferPath(q:BookingSearch){const children=q.childrenAges.filter(x=>x>=3&&x<12).length,infants=q.childrenAges.filter(x=>x<3).length,adults=q.adults+q.childrenAges.filter(x=>x>=12).length;return `/transfer-api/1.0/availability/en/from/IATA/${q.pickupAirport}/to/ATLAS/${q.dropoffHotel}/${q.checkIn}T${q.pickupTime}:00/${adults}/${children}/${infants}`;}
export async function searchTransfers(q:BookingSearch,fetcher:typeof fetch=fetch){const data=await hotelbedsRequest('vehicle',transferPath(q),undefined,fetcher);const offers:BookingOffer[]=[];for(const s of data.services||[]){if(typeof s.rateKey!=='string'||Number(s.maxPaxCapacity)<q.adults+q.childrenAges.length)continue;try{const c=currency(s.price?.currencyId);offers.push({id:`hb-transfer-${s.id}`,name:`${s.vehicle?.name||'Transfer'} · ${s.transferType||'Service'}`,kind:'vehicle',mode:'test',provider:'Hotelbeds evaluation API',price:price(s.price.totalAmount),currency:c,priceLabel:'One-way airport transfer · total',description:`Airport ${q.pickupAirport} to ${s.pickupInformation?.to?.description||'selected hotel'}. Pickup at ${q.pickupTime} on ${q.checkIn}.`,amenities:[String(s.category?.name||'Standard')],cancellation:cancellation(s.cancellationPolicies,c),terms:(s.content?.transferRemarks||[]).map((r:Obj)=>String(r.description||'')).join('\n').slice(0,10000)||'Review the pickup and baggage information with the supplier.',capacity:Number(s.maxPaxCapacity),rateKey:s.rateKey,serviceId:String(s.id),query:q});}catch{}}return offers;}
export async function refreshOffer(offer:BookingOffer){if(offer.kind==='hotel'){const data=await hotelbedsRequest('hotel','/hotel-api/1.0/checkrates',{rooms:[{rateKey:offer.rateKey}]});const h=data.hotel;if(!h)throw new Error('This hotel offer is no longer available.');for(const r of h.rooms||[])for(const rate of r.rates||[])if(rate.rateType==='BOOKABLE'){return hotelOffer(h,r,rate,offer.query);}throw new Error('Supplier could not confirm a bookable rate.');}
 if(offer.kind==='vehicle'){const found=(await searchTransfers(offer.query)).find(o=>o.id===offer.id);if(!found)throw new Error('This transfer is no longer available. Search again.');return found;}throw new Error('Unsupported supplier service.');}
export function hotelBookingPayload(offer:BookingOffer,contact:BookingContact,reference:string){let i=0;const paxes=[];for(let room=1;room<=offer.query.rooms;room++){for(let a=0;a<offer.query.adults;a++){const g=contact.guests?.[i++];if(!g)throw new Error('Enter each adult guest name.');paxes.push({roomId:room,type:'AD',name:g.name,surname:g.surname});}for(const age of offer.query.childrenAges){const g=contact.guests?.[i++];if(!g)throw new Error('Enter each child guest name.');paxes.push({roomId:room,type:'CH',age,name:g.name,surname:g.surname});}}return {holder:{name:contact.name,surname:contact.surname},rooms:[{rateKey:offer.rateKey,paxes}],clientReference:reference,tolerance:0};}
export async function confirmSupplier(offer:BookingOffer,contact:BookingContact,reference:string){
 if(offer.kind==='hotel'){const data=await hotelbedsRequest('hotel','/hotel-api/1.0/bookings',hotelBookingPayload(offer,contact,reference));const b=data.booking;if(!b?.reference||b.status!=='CONFIRMED')throw new Error('Supplier did not return a confirmed booking. Check the supplier dashboard before retrying.');return {reference:String(b.reference),status:String(b.status)};}
 if(offer.kind==='vehicle'){if(!contact.flightNumber||!/^[A-Z0-9]{2,7}$/i.test(contact.flightNumber))throw new Error('Enter a valid arrival flight number.');const data=await hotelbedsRequest('vehicle','/transfer-api/1.0/bookings',{language:'en',holder:{name:contact.name,surname:contact.surname,email:contact.email,phone:contact.phone},transfers:[{rateKey:offer.rateKey,transferDetails:[{type:'FLIGHT',direction:'ARRIVAL',code:contact.flightNumber.toUpperCase()}]}],clientReference:reference});const b=data.bookings?.[0];if(!b?.reference||b.status!=='CONFIRMED')throw new Error('Supplier did not confirm the transfer. Check the supplier dashboard before retrying.');return {reference:String(b.reference),status:String(b.status)};}
 throw new Error('Unsupported supplier booking.');
}
