import type {WebSocket} from 'uWebSockets.js';
import {createRequire} from 'node:module';
const {App}=createRequire(import.meta.url)('uWebSockets.js') as typeof import('uWebSockets.js');
import {readFileSync} from 'node:fs';
import {TokenBucket,MemoryCache} from './limits.ts';
import {ipc,routeCommand} from './ipc.ts';
import {redis} from './redis.ts';
const port=Number(process.env.PORT||3001),host=process.env.HOST||'127.0.0.1',origin=process.env.ALLOWED_ORIGIN||'http://localhost:3000',backend=process.env.NEXT_ORIGIN||'http://127.0.0.1:3000',anonymous=process.env.GATEWAY_ALLOW_ANONYMOUS==='true';
if(anonymous&&!['127.0.0.1','localhost','::1'].includes(host))throw new Error('Anonymous development mode must bind to loopback.');
const destinations=JSON.parse(readFileSync(new URL('../../../data/destinations.json',import.meta.url),'utf8')) as {id:string;name:string;state:string;latitude:number;longitude:number}[];
type Session={id:string;limit:TokenBucket;generating:number;last:number};
type Client={session?:Session;authenticating:boolean;closed:boolean;authTimer?:ReturnType<typeof setTimeout>;watch?:string};
const sessions=new Map<string,Session>(),connections=new Set<WebSocket<Client>>(),watchers=new Map<string,Set<WebSocket<Client>>>(),cache=new MemoryCache(),ingesting=new Set<string>();
function session(id:string){let s=sessions.get(id);if(!s){if(sessions.size>=2000)throw new Error('Gateway busy');s={id,limit:new TokenBucket(),generating:0,last:Date.now()};sessions.set(id,s);}s.last=Date.now();return s;}
async function authenticate(token:string){if(anonymous&&!token)return session('local-development');if(!process.env.SUPABASE_URL||!process.env.SUPABASE_ANON_KEY||!token)throw new Error('Sign in to use the gateway');const r=await fetch(process.env.SUPABASE_URL+'/auth/v1/user',{headers:{Authorization:'Bearer '+token,apikey:process.env.SUPABASE_ANON_KEY},signal:AbortSignal.timeout(5000)});const user=await r.json();if(!r.ok||!user.id)throw new Error('Invalid session');return session(user.id);}
function send(ws:WebSocket<Client>,data:unknown){if(ws.getUserData().closed)return;if(ws.getBufferedAmount()>128000){ws.end(1013,'Slow connection');return;}ws.send(JSON.stringify(data));}
async function refreshWeather(name:string){if(ingesting.has(name))return;ingesting.add(name);try{const key='travelsetu:weather:v1:'+name;let value=cache.get(key);if(!value){try{const saved=await redis(['GET',key]);if(saved)value=JSON.parse(saved);}catch{}if(!value){const date=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata'}).format(new Date());const r=await fetch(backend+'/api/weather',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({destination:name,startDate:date,endDate:date}),signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('Weather unavailable');value=await r.json();redis(['SET',key,JSON.stringify(value),'EX','300']).catch(()=>{});}cache.set(key,value);}for(const ws of watchers.get(name)||[])send(ws,{type:'weather',destination:name,data:value});}catch{for(const ws of watchers.get(name)||[])send(ws,{type:'error',error:'Weather feed unavailable'});}finally{ingesting.delete(name);}}
function unwatch(ws:WebSocket<Client>){const key=ws.getUserData().watch;if(key){watchers.get(key)?.delete(ws);if(!watchers.get(key)?.size)watchers.delete(key);}}
if(process.argv.includes('--check')){console.log('Gateway modules and configuration loaded.');process.exit(0);}
const app=App();
app.get('/health',(res)=>{res.writeHeader('Content-Type','application/json').end(JSON.stringify({ok:true,service:'travelsetu-gateway',cache:process.env.REDIS_URL?'optional-redis':'bounded-memory',clients:connections.size}));});
app.options('/v1/plan',(res,req)=>{if(req.getHeader('origin')!==origin){res.writeStatus('403 Forbidden').end();return;}res.writeHeader('Access-Control-Allow-Origin',origin).writeHeader('Vary','Origin').writeHeader('Access-Control-Allow-Methods','POST, OPTIONS').writeHeader('Access-Control-Allow-Headers','Content-Type, Authorization, Accept').end();});
app.post('/v1/plan',(res,req)=>{const requestOrigin=req.getHeader('origin'),token=req.getHeader('authorization').replace(/^Bearer /i,'');if(requestOrigin!==origin){res.writeStatus('403 Forbidden').end();return;}let aborted=false,headersSent=false,body=Buffer.alloc(0),drain:(()=>void)|undefined;const abort=new AbortController();res.onAborted(()=>{aborted=true;abort.abort();drain?.();});res.onData((chunk,last)=>{if(aborted)return;body=Buffer.concat([body,Buffer.from(chunk)]);if(body.length>16000){res.writeStatus('413 Payload Too Large').end();aborted=true;abort.abort();return;}if(last)void proxy();});
 async function proxy(){let user:Session|undefined,acquired=false;try{user=await authenticate(token);if(aborted)return;if(!user.limit.take()||user.generating>=2){res.cork(()=>res.writeStatus('429 Too Many Requests').writeHeader('Access-Control-Allow-Origin',origin).end('Too many requests'));return;}user.generating++;acquired=true;const timeout=setTimeout(()=>abort.abort(),175000);let response:Response;try{response=await fetch(backend+'/api/gemini',{method:'POST',headers:{'Content-Type':'application/json',Accept:'text/event-stream',Origin:new URL(backend).origin},body,signal:abort.signal});if(aborted)return;headersSent=true;res.cork(()=>res.writeStatus(String(response.status)+' '+(response.statusText||'OK')).writeHeader('Access-Control-Allow-Origin',origin).writeHeader('Vary','Origin').writeHeader('Content-Type',response.headers.get('content-type')||'application/json').writeHeader('Cache-Control','no-cache, no-transform'));if(response.body){for await(const chunk of response.body as any){if(aborted)break;const writable=res.write(chunk);if(!writable)await new Promise<void>(resolve=>{drain=resolve;res.onWritable(()=>{drain=undefined;resolve();return true;});});}}if(!aborted)res.end();}finally{clearTimeout(timeout);}}
 catch{if(!aborted&&headersSent){res.end('event: error\ndata: {"error":"Gateway stream interrupted. Your draft is saved."}\n\n');}else if(!aborted)res.cork(()=>res.writeStatus('503 Service Unavailable').writeHeader('Access-Control-Allow-Origin',origin).end(JSON.stringify({error:'Gateway could not connect or authenticate. Check configuration.'})));}finally{if(user&&acquired)user.generating--;}}
});
app.ws<Client>('/ws',{maxPayloadLength:16000,maxBackpressure:128000,closeOnBackpressureLimit:true,idleTimeout:60,sendPingsAutomatically:true,
 upgrade:(res,req,context)=>{if(req.getHeader('origin')!==origin||connections.size>=512){res.writeStatus('403 Forbidden').end();return;}res.upgrade({authenticating:false,closed:false},req.getHeader('sec-websocket-key'),req.getHeader('sec-websocket-protocol'),req.getHeader('sec-websocket-extensions'),context);},
 open:ws=>{connections.add(ws);ws.getUserData().authTimer=setTimeout(()=>{if(!ws.getUserData().session)ws.end(1008,'Authentication required');},10000);send(ws,{type:'hello',authenticationRequired:!anonymous});},
 message:async(ws,buffer,binary)=>{const state=ws.getUserData();if(binary){ws.end(1003,'Text frames only');return;}try{const data=JSON.parse(Buffer.from(buffer).toString());if(!state.session){if(data.type!=='auth'||state.authenticating)throw new Error('Authenticate first');state.authenticating=true;try{state.session=await authenticate(String(data.token||''));if(state.closed)return;clearTimeout(state.authTimer);send(ws,{type:'ready'});}finally{state.authenticating=false;}return;}if(!state.session.limit.take())throw new Error('Rate limit reached; slow down');state.session.last=Date.now();
 if(data.type==='search'){const q=String(data.query||'').trim().slice(0,100).toLowerCase();send(ws,{type:'search',requestId:String(data.requestId||'').slice(0,80),results:q?destinations.filter(d=>(d.name+' '+d.state).toLowerCase().includes(q)).slice(0,8).map(d=>({id:d.id,name:d.name,state:d.state})):[]});}
 else if(data.type==='watch-weather'){const d=destinations.find(d=>d.name===data.destination);if(!d)throw new Error('Unknown destination');unwatch(ws);state.watch=d.name;if(!watchers.has(d.name))watchers.set(d.name,new Set());watchers.get(d.name)!.add(ws);await refreshWeather(d.name);}
 else if(data.type==='unwatch-weather')unwatch(ws);
 else if(data.type==='route-order'){if(state.session.generating>=2)throw new Error('Compute is busy');const command=routeCommand(data.points);state.session.generating++;try{const result=await ipc(command);send(ws,{type:'route-order',requestId:data.requestId,result});}finally{state.session.generating--;}}
 else if(data.type==='ping')send(ws,{type:'pong'});else throw new Error('Unsupported message');
 }catch(e){send(ws,{type:'error',error:(e as Error).message});}},
 close:ws=>{ws.getUserData().closed=true;clearTimeout(ws.getUserData().authTimer);unwatch(ws);connections.delete(ws);}
});
const timer=setInterval(()=>{for(const name of watchers.keys())void refreshWeather(name);for(const [id,s] of sessions)if(!s.generating&&s.last<Date.now()-3600000&&!Array.from(connections).some(w=>w.getUserData().session?.id===id))sessions.delete(id);},300000);timer.unref();
app.listen(host,port,socket=>{if(!socket){console.error('Gateway could not listen');process.exitCode=1;return;}console.log(`Gateway listening on ${host}:${port}; allowed origin ${origin}`);});
